// Package layout is selfdoc's declaration of the per-repository directories it
// owns, and the single authority for every path it reads or writes inside them.
//
// A repository keeps one hidden directory at its root, [Root], holding
// function-named directories rather than tool-named ones: docs/ is the pages a
// person writes, .docs-state/ is what selfdoc generates and the repository
// commits, .docs-cache/ is what selfdoc generates and the repository does not
// commit, posts/ is the blog, vocabulary/ is the project's word lists. Another
// tool's state lives beside them under its own function name, never under a
// tool's name.
//
// # Names
//
// A directory a person writes carries its function name as it is; a directory
// a tool generates carries it behind a leading dot, so the hand-edited
// directories are the ones a directory listing shows. The dot is derived from
// the side the declaration states ([Directory.DiskName]), never typed beside
// it, and [Validate] refuses a directory selfdoc owns whose dot disagrees with
// its side. The dot means that at the top level of [Root] only: deeper down it
// means nothing, and selfdoc's committed directories hold no dotted entries.
//
// # Ownership
//
// Every directory under [Root] has exactly one owner tool, declared in the
// [ManifestFileName] the directory itself carries. The manifest is the
// permission to write: [EnsureDir] refuses a directory whose manifest does not
// name selfdoc, printing the file and the line to put in it. Manifests are
// written by the repository's deliberate acts only: adopting selfdoc with
// `selfdoc init` ([GrantInit]), and moving off the previous layout with
// `selfdoc layout migrate`, where the previous manifests naming selfdoc are the
// grant. A manifest is also what makes a directory with no content yet exist
// in git. Reading and writing are open to anyone; the owner decides
// whether what was written is acceptable, which is what [Validate] answers.
//
// # Sides
//
// A directory is entirely handwritten or entirely generated -- never both. The
// side is a property of the function, so it is declared here once rather than
// per repository, and [Validate] holds the tree to it: a generated page in a
// handwritten directory, or a handwritten page in a generated one, is a defect
// with a named remedy.
//
// # The ignore files
//
// [Root] holds directories only, with [RootFiles] as the exceptions, so the
// ignore rules a directory needs sit inside it: each uncommitted directory
// selfdoc owns carries its own [IgnoreFileName], derived from the commitment
// its declaration states. Its contents are ignored, and its manifest and the
// ignore file itself are not, so the permission travels with the repository
// while the contents do not.
package layout

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/stricttools/selfdoc/internal/effects"
	"github.com/stricttools/selfdoc/internal/scripts"
)

// Root is the one directory a repository's tool-owned state lives in,
// relative to the repository root. It starts with a dot as .git does: the
// tools that make a project commit these files hide them, so the project's own
// top level stays tidy.
const Root = ".strictmetadata"

// Owner is the name selfdoc is declared under in a directory's manifest.
const Owner = "selfdoc"

// ManifestFileName is the ownership declaration a directory under [Root]
// carries, inside the directory it speaks for.
const ManifestFileName = "manifest.toml"

// OwnerKey is the one key a manifest declares. The generated validator refuses
// a manifest carrying any other key.
const OwnerKey = "owner"

// The schema's format-version gate, which [ReadDirectoryManifest] supplies
// rather than the file. A manifest that declares it itself is refused, so the
// key has exactly one author and a manifest on disk stays one line long.
const (
	formatVersionKey      = "format_version"
	manifestFormatVersion = SCHEMA_FORMAT_VERSION
)

// IgnoreFileName is the ignore file a directory under [Root] carries. It
// starts with a dot because git reads it under no other name, not because it
// is generated.
const IgnoreFileName = ".gitignore"

// RootFiles are the files [Root] may hold beside its directories: go.mod, the
// stub module that keeps the tree out of a Go module's zip.
var RootFiles = []string{"go.mod"}

// MoveScript is the script that moves a repository off the layout selfdoc used
// before this one, as it is spelled inside selfdoc's own checkout. A refusal
// prints the fetch-and-run commands instead, because the repository being
// refused does not have this path.
var MoveScript = scripts.RepoPath(scripts.Move)

// GeneratedMarkerPrefix opens the HTML comment every page selfdoc generates
// carries under its frontmatter. It is what tells a generated page from a
// handwritten one on disk, which is how [Validate] checks a directory's side.
const GeneratedMarkerPrefix = "<!-- generated by selfdoc gen"

// Side is whether a directory's contents are written by a person or by a tool.
type Side string

// The two sides. A directory is entirely one or entirely the other.
const (
	Handwritten Side = "handwritten"
	Generated   Side = "generated"
)

// Commitment is whether a directory's contents belong in the repository.
type Commitment string

// The two commitments. An uncommitted directory carries its own ignore file.
const (
	Committed   Commitment = "committed"
	Uncommitted Commitment = "uncommitted"
)

// The names of the function directories selfdoc claims, relative to [Root].
const (
	DocsName       = "docs"
	DocsStateName  = "docs-state"
	DocsCacheName  = "docs-cache"
	PostsName      = "posts"
	VocabularyName = "vocabulary"
)

// The function directories, as paths relative to the repository root, in slash
// form. Each is derived from the declaration, so a directory's on-disk name is
// written in one place: [Directory.DiskName].
var (
	DocsRel       = declaredRel(DocsName)
	DocsStateRel  = declaredRel(DocsStateName)
	DocsCacheRel  = declaredRel(DocsCacheName)
	PostsRel      = declaredRel(PostsName)
	VocabularyRel = declaredRel(VocabularyName)
)

// The files and subdirectories selfdoc keeps inside its function directories,
// as paths relative to the repository root, in slash form.
var (
	// GeneratedPagesRel is the second docs root: the pages selfdoc generates,
	// merged into one URL namespace with the handwritten root at build time.
	GeneratedPagesRel = DocsStateRel + "/pages"
	// ManifestRel is the record of what a build published.
	ManifestRel = DocsStateRel + "/manifest.json"
	// PostManifestRel is the posts-only manifest the assembly's post publisher
	// reads.
	PostManifestRel = DocsStateRel + "/post-manifest.json"
	// RevisionsRel is the post revision record.
	RevisionsRel = DocsStateRel + "/revisions.json"
	// HashesDirRel holds the content and description hash baselines.
	HashesDirRel = DocsStateRel + "/hashes"
	// HashesRel is the hash store itself.
	HashesRel = HashesDirRel + "/hashes.json"
	// DataRel is where a sandboxed gen-data script writes its output.
	DataRel = DocsStateRel + "/data"
	// OutputRel is the built site.
	OutputRel = DocsCacheRel + "/build"
	// VersionsRel holds one extracted checkout per archived version.
	VersionsRel = DocsCacheRel + "/versions"
	// TermsRel is the project's accepted and rejected vocabulary.
	TermsRel = VocabularyRel + "/terms.toml"
	// ReviewRel is the vocabulary's review list: words proposed for
	// acceptance that nobody has approved yet.
	ReviewRel = VocabularyRel + "/review.toml"
)

// The declared values of the config keys that name a layout directory. A
// project that declares nothing gets these, and a project that declares
// something else has to keep it under [Root].
var (
	DocsDefault   = DocsRel + "/"
	OutputDefault = OutputRel + "/"
	PostsDefault  = PostsRel + "/"
)

// Directory is one function directory selfdoc claims: what it is for, which
// side of the authorship line it sits on, whether the repository commits it,
// and the paths it replaced.
type Directory struct {
	// Name is the directory's function name. The name it carries on disk is
	// [Directory.DiskName].
	Name string
	// Side is whether people or selfdoc write its contents.
	Side Side
	// Commitment is whether the repository carries its contents.
	Commitment Commitment
	// Description says what the directory holds.
	Description string
	// DeprecatedNames are the paths this directory replaced, as they were
	// spelled relative to the repository root. A repository that still has
	// one of them is refused.
	DeprecatedNames []string
}

// declared is the whole claim, in the order a dump prints it.
var declared = []Directory{
	{
		Name:            DocsName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The pages a person writes, the underscore-prefixed templates they include, and the docs configuration that sits beside them.",
		DeprecatedNames: []string{"docs/", EarlierRoot + "/" + DocsName + "/", PreviousRoot + "/" + DocsName + "/"},
	},
	{
		Name:            DocsStateName,
		Side:            Generated,
		Commitment:      Committed,
		Description:     "What selfdoc generates and the repository keeps: the manifests, the hash baselines, the post revisions, the generated data files, and the generated pages.",
		DeprecatedNames: []string{".selfdoc/", EarlierRoot + "/" + DocsStateName + "/", PreviousRoot + "/." + DocsStateName + "/"},
	},
	{
		Name:            DocsCacheName,
		Side:            Generated,
		Commitment:      Uncommitted,
		Description:     "What selfdoc generates and the repository throws away: the built site and one extracted checkout per archived version.",
		DeprecatedNames: []string{"docs/_build/", ".selfdoc/cache/", EarlierRoot + "/" + DocsCacheName + "/", PreviousRoot + "/." + DocsCacheName + "/"},
	},
	{
		Name:            PostsName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The project's blog posts.",
		DeprecatedNames: []string{".selfdoc/posts/", EarlierRoot + "/" + PostsName + "/", PreviousRoot + "/" + PostsName + "/"},
	},
	{
		Name:            VocabularyName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The project's accepted and rejected vocabulary and its review list, read by the spell check.",
		DeprecatedNames: []string{EarlierRoot + "/" + VocabularyName + "/", PreviousRoot + "/" + VocabularyName + "/"},
	},
}

// generatedPrefix is what a generated directory's name starts with on disk,
// at the top level of [Root].
const generatedPrefix = "."

// DiskName is the name the directory carries under [Root]: its function name,
// behind a leading dot when selfdoc generates its contents.
func (d Directory) DiskName() string {
	if d.Side == Generated {
		return generatedPrefix + d.Name
	}
	return d.Name
}

// Rel is the directory as a path relative to the repository root, in slash
// form.
func (d Directory) Rel() string {
	return Root + "/" + d.DiskName()
}

// declaredRel is one claimed directory's relative path. It is only ever called
// with the names this package declares, so a miss is a defect in this file.
func declaredRel(name string) string {
	dir, ok := Lookup(name)
	if !ok {
		panic("layout: " + name + " is not a declared directory")
	}
	return dir.Rel()
}

// DiskNameOf is the name a directory carries under [Root]: the derived name
// for a directory selfdoc claims, and the name as given for any other.
func DiskNameOf(name string) string {
	if dir, ok := Lookup(name); ok {
		return dir.DiskName()
	}
	return name
}

// LookupDiskName returns the claimed directory an entry under [Root] is, by
// the name it carries on disk. An entry whose dot disagrees with the claimed
// directory's side is not that directory.
func LookupDiskName(entry string) (Directory, bool) {
	for _, dir := range declared {
		if dir.DiskName() == entry {
			return dir, true
		}
	}
	return Directory{}, false
}

// LookupFunction returns the claimed directory an entry under [Root] names by
// its function, whatever its dot says: the entry with its one leading dot
// removed, when that is a function selfdoc claims.
func LookupFunction(entry string) (Directory, bool) {
	return Lookup(strings.TrimPrefix(entry, generatedPrefix))
}

// Declared returns the directories selfdoc claims, in declaration order.
func Declared() []Directory {
	out := make([]Directory, len(declared))
	copy(out, declared)
	return out
}

// Lookup returns the declaration of one claimed directory.
func Lookup(name string) (Directory, bool) {
	for _, dir := range declared {
		if dir.Name == name {
			return dir, true
		}
	}
	return Directory{}, false
}

// Path joins a repository root with one of this package's slash-form relative
// paths, in the operating system's own spelling.
func Path(baseDir, rel string) string {
	return filepath.Join(baseDir, filepath.FromSlash(rel))
}

// UnderRoot reports whether a declared path names something inside [Root].
// A project may spell its docs and output paths as it likes as long as they
// live in the layout.
func UnderRoot(declaredPath string) bool {
	clean := path.Clean(strings.TrimRight(filepath.ToSlash(declaredPath), "/"))
	return clean == Root || strings.HasPrefix(clean, Root+"/")
}

// EntryOf returns the entry directly under [Root] a relative path sits in, as
// it is spelled on disk.
func EntryOf(rel string) (string, bool) {
	clean := strings.TrimRight(filepath.ToSlash(rel), "/")
	if !strings.HasPrefix(clean, Root+"/") {
		return "", false
	}
	rest := strings.TrimPrefix(clean, Root+"/")
	if rest == "" {
		return "", false
	}
	return strings.SplitN(rest, "/", 2)[0], true
}

// FunctionOf returns the function of the claimed directory a relative path
// sits in. A path under [Root] in a directory selfdoc does not claim, or in
// one whose dot disagrees with the claimed side, sits in none.
func FunctionOf(rel string) (string, bool) {
	entry, ok := EntryOf(rel)
	if !ok {
		return "", false
	}
	dir, claimed := LookupDiskName(entry)
	if !claimed {
		return "", false
	}
	return dir.Name, true
}

// DirectoryManifestRel is a directory's ownership manifest, as a path relative
// to the repository root, in slash form. name is a function name: a directory
// selfdoc claims resolves to the name it carries on disk.
func DirectoryManifestRel(name string) string {
	return entryManifestRel(DiskNameOf(name))
}

// entryManifestRel is the manifest of one entry under [Root], by the name the
// entry carries on disk.
func entryManifestRel(entry string) string {
	return Root + "/" + entry + "/" + ManifestFileName
}

// DirectoryManifestPath is where a directory's ownership manifest sits, in the
// operating system's own spelling.
func DirectoryManifestPath(baseDir, name string) string {
	return Path(baseDir, DirectoryManifestRel(name))
}

// DirectoryManifestContent renders the manifest that declares one tool the
// owner of a directory. Every refusal that asks for a manifest prints from
// here, so the text a person is told to write is generated from the
// declaration rather than typed beside it.
func DirectoryManifestContent(owner string) string {
	return OwnerKey + " = " + strconv.Quote(owner) + "\n"
}

// ReadDirectoryManifest reads and validates one directory's ownership
// manifest.
//
// strictspec is the boundary validator: the file is checked against
// .strictspec/directory-manifest.schema.toml by the generated validator in
// this package, so a manifest that reaches a caller declares an owner and
// nothing else. A missing manifest is returned as the underlying
// [os.ErrNotExist], which callers answer with the file to create.
//
// The schema's format-version gate is supplied here rather than written into
// the file, the way a frontmatter block's is: a manifest on disk is the one
// [OwnerKey] line, and a file that declares the gate itself is refused, so the
// key has exactly one author.
func ReadDirectoryManifest(baseDir, name string) (*DirectoryManifest, error) {
	return readEntryManifest(baseDir, DiskNameOf(name))
}

// readEntryManifest reads and validates the manifest of one entry under
// [Root], named as it is spelled on disk.
func readEntryManifest(baseDir, entry string) (*DirectoryManifest, error) {
	return readManifestFile(Path(baseDir, entryManifestRel(entry)))
}

// readManifestFile reads and validates one ownership manifest by its path.
func readManifestFile(manifestPath string) (*DirectoryManifest, error) {
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, err
	}
	if declaresFormatVersion(string(raw)) {
		return nil, fmt.Errorf(
			"%s declares %q, which the reader supplies: remove it, so the manifest is the one %s line",
			manifestPath, formatVersionKey, OwnerKey)
	}
	augmented := string(raw)
	if augmented != "" && !strings.HasSuffix(augmented, "\n") {
		augmented += "\n"
	}
	augmented += fmt.Sprintf("%s = %d\n", formatVersionKey, manifestFormatVersion)
	document, diags := ValidateBytes([]byte(augmented), "toml")
	if len(diags) > 0 {
		var detail strings.Builder
		for _, diagnostic := range diags {
			fmt.Fprintf(&detail, "\n  %s: %s [%s]",
				diagnostic.Path, diagnostic.Message, diagnostic.Code)
		}
		return nil, fmt.Errorf(
			"%s is not a valid ownership manifest. It declares %s and nothing else:%s",
			manifestPath, OwnerKey, detail.String())
	}
	return document, nil
}

// declaresFormatVersion reports whether a manifest's own text assigns the gate
// key that [ReadDirectoryManifest] supplies.
func declaresFormatVersion(text string) bool {
	for _, line := range strings.Split(text, "\n") {
		rest, found := strings.CutPrefix(strings.TrimSpace(line), formatVersionKey)
		if found && strings.HasPrefix(strings.TrimSpace(rest), "=") {
			return true
		}
	}
	return false
}

// SharedOwner is the owner a directory several tools share names in its
// manifest (the options directory and the upstream directory). strictspec
// holds the schemas those directories are validated against, and it is a
// library every reading tool links rather than a command, so no PATH lookup
// can answer for it.
const SharedOwner = "strictspec"

// CLIOwner is the owner the directories a strictcli program's schema and test
// coverage live in name in their manifests (.cli-schema and
// .cli-test-coverage). strictcli is a library its programs link rather than a
// command, so no PATH lookup can answer for it either.
const CLIOwner = "strictcli"

// LibraryOwners are the owners a manifest may name that are libraries rather
// than commands.
var LibraryOwners = []string{SharedOwner, CLIOwner}

// KnownOwner reports whether a manifest names an owner this machine has:
// selfdoc itself, one of [LibraryOwners], or any name PATH answers with an
// executable.
func KnownOwner(owner string) bool {
	if owner == Owner {
		return true
	}
	for _, library := range LibraryOwners {
		if owner == library {
			return true
		}
	}
	_, err := exec.LookPath(owner)
	return err == nil
}

// EnsureOwned answers whether selfdoc may write into one of the directories
// under [Root] in this repository.
//
// The manifest is the permission. A directory carrying none, or one naming
// another tool, is refused -- the first with the file and the line to write,
// which no command but `selfdoc init` writes.
func EnsureOwned(baseDir, name string) error {
	manifest, err := ReadDirectoryManifest(baseDir, name)
	if errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf(
			"selfdoc may not write into %s: it carries no %s, and the manifest is the permission. Create %s holding this line:\n%s",
			Root+"/"+DiskNameOf(name), ManifestFileName, DirectoryManifestRel(name),
			strings.TrimRight(DirectoryManifestContent(Owner), "\n"))
	}
	if err != nil {
		return err
	}
	if manifest.Owner != Owner {
		return fmt.Errorf(
			"selfdoc may not write into %s: %s declares %q as its owner, not %q",
			Root+"/"+DiskNameOf(name), DirectoryManifestRel(name), manifest.Owner, Owner)
	}
	return nil
}

// InitDirectories are the directories `selfdoc init` grants selfdoc: the
// pages, the generated state and the cache every project writes from its first
// build on, and the vocabulary its spell check reads.
var InitDirectories = []string{DocsName, DocsStateName, DocsCacheName, VocabularyName}

// GrantInit writes the ownership manifests of [InitDirectories] that are
// missing, naming selfdoc, and the ignore file of each uncommitted one. It
// returns the slash-form relative paths of the manifests it wrote and of every
// uncommitted directory's ignore file.
//
// It is the adopting act a repository performs by running `selfdoc init`. A
// manifest already naming selfdoc is kept
// as it stands, and one naming another tool refuses the whole grant before
// anything is written: that directory is the other tool's.
func GrantInit(h *effects.Handle, baseDir string) ([]string, error) {
	var missing []string
	for _, name := range InitDirectories {
		manifest, err := ReadDirectoryManifest(baseDir, name)
		switch {
		case errors.Is(err, os.ErrNotExist):
			missing = append(missing, name)
		case err != nil:
			return nil, err
		case manifest.Owner != Owner:
			return nil, fmt.Errorf(
				"selfdoc init may not adopt %s: %s declares %q as its owner, not %q",
				Root+"/"+DiskNameOf(name), DirectoryManifestRel(name), manifest.Owner, Owner)
		}
	}
	written := make([]string, 0, len(missing))
	for _, name := range missing {
		if err := h.MkdirAll(Path(baseDir, declaredRel(name))); err != nil {
			return nil, err
		}
		if err := h.AtomicWrite(DirectoryManifestPath(baseDir, name),
			[]byte(DirectoryManifestContent(Owner)), effects.ModeDefault); err != nil {
			return nil, err
		}
		written = append(written, DirectoryManifestRel(name))
	}
	for _, name := range InitDirectories {
		if dir, _ := Lookup(name); dir.Commitment != Uncommitted {
			continue
		}
		if err := h.MkdirAll(Path(baseDir, declaredRel(name))); err != nil {
			return nil, err
		}
		if err := WriteDirectoryIgnore(h, baseDir, name); err != nil {
			return nil, err
		}
		written = append(written, DirectoryIgnoreRel(name))
	}
	return written, nil
}

// EnsureDir creates a directory inside one of selfdoc's function directories,
// after checking the manifest that permits it, and brings that function
// directory's ignore file up to date when it is uncommitted.
//
// rel is one of this package's slash-form relative paths. Creating anything
// under [Root] goes through here, so no path can reach the filesystem without
// its owning manifest having been read.
func EnsureDir(h *effects.Handle, baseDir, rel string) error {
	entry, ok := EntryOf(rel)
	if !ok {
		return fmt.Errorf("%q is not a path under %s", rel, Root)
	}
	dir, claimed := LookupDiskName(entry)
	if !claimed {
		return fmt.Errorf("selfdoc does not claim %s", Root+"/"+entry)
	}
	name := dir.Name
	if err := EnsureOwned(baseDir, name); err != nil {
		return err
	}
	if err := h.MkdirAll(Path(baseDir, rel)); err != nil {
		return err
	}
	return WriteDirectoryIgnore(h, baseDir, name)
}

// The comments an earlier selfdoc wrapped its block of the ignore file at the
// top of a root in. [WithoutIgnoreBlock] reads them, so a move off that file
// can tell selfdoc's lines from another tool's.
const (
	ignoreBegin = "# BEGIN selfdoc -- derived from selfdoc's layout declaration"
	ignoreEnd   = "# END selfdoc"
)

// directoryIgnoreContent is what the ignore file of an uncommitted directory
// selfdoc owns holds: everything in the directory is ignored except the
// directory's manifest and the ignore file itself. The manifest is the
// permission to write into the directory, and a permission that git did not
// carry would have to be written again in every fresh checkout -- including
// the ones a multi-version build extracts out of git tags.
const directoryIgnoreContent = "# Written by selfdoc from its layout declaration: what this directory holds\n" +
	"# is not committed; its manifest and this file are.\n" +
	"*\n" +
	"!" + IgnoreFileName + "\n" +
	"!" + ManifestFileName + "\n"

// DirectoryIgnoreContent returns what an uncommitted directory's ignore file
// holds.
func DirectoryIgnoreContent() string { return directoryIgnoreContent }

// DirectoryIgnoreRel returns where the ignore file of the directory with the
// given function name sits, relative to the repository root, in slash form.
func DirectoryIgnoreRel(name string) string {
	return declaredRel(name) + "/" + IgnoreFileName
}

// IgnoredDirectories are the directories selfdoc claims whose contents the
// repository does not commit, each of which carries its own ignore file.
func IgnoredDirectories() []Directory {
	var ignored []Directory
	for _, dir := range declared {
		if dir.Commitment == Uncommitted {
			ignored = append(ignored, dir)
		}
	}
	return ignored
}

// WriteDirectoryIgnore brings the ignore file of the directory with the given
// function name up to date, writing nothing when the directory is committed or
// the file already holds what it should.
func WriteDirectoryIgnore(h *effects.Handle, baseDir, name string) error {
	dir, ok := Lookup(name)
	if !ok || dir.Commitment != Uncommitted {
		return nil
	}
	target := Path(baseDir, DirectoryIgnoreRel(name))
	existing, err := os.ReadFile(target)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if string(existing) == directoryIgnoreContent {
		return nil
	}
	return h.AtomicWrite(target, []byte(directoryIgnoreContent), effects.ModeDefault)
}

// RootIgnoreRel is the ignore file an earlier selfdoc derived at the top of
// [Root], which `selfdoc layout migrate` converts into one per directory.
var RootIgnoreRel = Root + "/" + IgnoreFileName

// WithoutIgnoreBlock returns an ignore file's content with selfdoc's block
// removed and every other line kept, for the ignore file a move leaves behind.
func WithoutIgnoreBlock(existing string) string {
	var before, after []string
	inBlock, sawBlock := false, false
	for _, line := range strings.Split(strings.ReplaceAll(existing, "\r\n", "\n"), "\n") {
		switch {
		case strings.TrimSpace(line) == ignoreBegin:
			inBlock, sawBlock = true, true
		case strings.TrimSpace(line) == ignoreEnd:
			inBlock = false
		case inBlock:
		case sawBlock:
			after = append(after, line)
		default:
			before = append(before, line)
		}
	}
	lines := trimBlankEdges(before)
	if rest := trimBlankEdges(after); len(rest) > 0 {
		if len(lines) > 0 {
			lines = append(lines, "")
		}
		lines = append(lines, rest...)
	}
	if len(lines) == 0 {
		return ""
	}
	return strings.Join(lines, "\n") + "\n"
}

// trimBlankEdges drops the blank lines at both ends of a slice, so joining
// sections never doubles a blank line.
func trimBlankEdges(lines []string) []string {
	start, end := 0, len(lines)
	for start < end && strings.TrimSpace(lines[start]) == "" {
		start++
	}
	for end > start && strings.TrimSpace(lines[end-1]) == "" {
		end--
	}
	return lines[start:end]
}
