// Package layout is selfdoc's declaration of the per-repository directories it
// owns, and the single authority for every path it reads or writes inside them.
//
// A repository keeps one hidden directory at its root, [Root], holding
// function-named directories rather than tool-named ones: docs/ is the pages a
// person writes, docs-state/ is what selfdoc generates and the repository
// commits, docs-cache/ is what selfdoc generates and the repository does not
// commit, posts/ is the blog, vocabulary/ is the project's word lists. Another
// tool's state lives beside them under its own function name.
//
// # Ownership
//
// Every directory under [Root] has exactly one owner tool, declared in the
// [ManifestFileName] the directory itself carries. The manifest is the
// permission to write: [EnsureDir] refuses a directory whose manifest does not
// name selfdoc, printing the file and the line to put in it, and selfdoc never
// writes one itself. A manifest is also what makes a directory with no content
// yet exist in git. Reading and writing are open to anyone; the owner decides
// whether what was written is acceptable, which is what [Validate] answers.
//
// # Sides
//
// A directory is entirely handwritten or entirely generated -- never both. The
// side is a property of the function, so it is declared here once rather than
// per repository, and [Validate] holds the tree to it: a generated page in a
// handwritten directory, or a handwritten page in a generated one, is a defect
// with a named remedy.
//
// # The derived ignore file
//
// git needs one file inside [Root] to keep the uncommitted directories out of
// the repository. It is derived, at [Root]/[IgnoreFileName], from the
// commitment each tool declares: an uncommitted directory's contents are
// ignored and its manifest is not, so the permission travels with the
// repository while the contents do not. selfdoc owns only the block between
// its two marker comments and leaves every other line of that file alone, so
// several tools can write their own blocks into one file.
package layout

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/stricttools/selfdoc/internal/effects"
	"github.com/stricttools/selfdoc/internal/scripts"
)

// Root is the one hidden directory a repository's tool-owned state lives in,
// relative to the repository root.
const Root = ".stricttools"

// Owner is the name selfdoc is declared under in a directory's manifest.
const Owner = "selfdoc"

// ManifestFileName is the ownership declaration a directory under [Root]
// carries, inside the directory it speaks for.
const ManifestFileName = "manifest.toml"

// OwnerKey is the one key a manifest declares. The generated validator refuses
// a manifest carrying any other key.
const OwnerKey = "owner"

// The schema's format-version gate, which [ReadDirectoryManifest] supplies
// rather than the file. A manifest that declares it itself is refused, so the
// key has exactly one author and a manifest on disk stays one line long.
const (
	formatVersionKey      = "format_version"
	manifestFormatVersion = SchemaFormatVersion
)

// IgnoreFileName is the derived ignore file inside [Root], and the one entry
// there allowed to start with a dot.
const IgnoreFileName = ".gitignore"

// MoveScript is the script that moves a repository off the layout selfdoc used
// before this one, as it is spelled inside selfdoc's own checkout. A refusal
// prints the fetch-and-run commands instead, because the repository being
// refused does not have this path.
var MoveScript = scripts.RepoPath(scripts.Move)

// GeneratedMarkerPrefix opens the HTML comment every page selfdoc generates
// carries under its frontmatter. It is what tells a generated page from a
// handwritten one on disk, which is how [Validate] checks a directory's side.
const GeneratedMarkerPrefix = "<!-- generated by selfdoc gen"

// Side is whether a directory's contents are written by a person or by a tool.
type Side string

// The two sides. A directory is entirely one or entirely the other.
const (
	Handwritten Side = "handwritten"
	Generated   Side = "generated"
)

// Commitment is whether a directory's contents belong in the repository.
type Commitment string

// The two commitments. An uncommitted directory contributes one line to the
// derived ignore file.
const (
	Committed   Commitment = "committed"
	Uncommitted Commitment = "uncommitted"
)

// The names of the function directories selfdoc claims, relative to [Root].
const (
	DocsName       = "docs"
	DocsStateName  = "docs-state"
	DocsCacheName  = "docs-cache"
	PostsName      = "posts"
	VocabularyName = "vocabulary"
)

// The function directories, as paths relative to the repository root, in slash
// form.
const (
	DocsRel       = Root + "/" + DocsName
	DocsStateRel  = Root + "/" + DocsStateName
	DocsCacheRel  = Root + "/" + DocsCacheName
	PostsRel      = Root + "/" + PostsName
	VocabularyRel = Root + "/" + VocabularyName
)

// The files and subdirectories selfdoc keeps inside its function directories,
// as paths relative to the repository root, in slash form.
const (
	// GeneratedPagesRel is the second docs root: the pages selfdoc generates,
	// merged into one URL namespace with the handwritten root at build time.
	GeneratedPagesRel = DocsStateRel + "/pages"
	// ManifestRel is the record of what a build published.
	ManifestRel = DocsStateRel + "/manifest.json"
	// PostManifestRel is the posts-only manifest the assembly's post publisher
	// reads.
	PostManifestRel = DocsStateRel + "/post-manifest.json"
	// RevisionsRel is the post revision sidecar.
	RevisionsRel = DocsStateRel + "/revisions.json"
	// HashesDirRel holds the content and description hash baselines.
	HashesDirRel = DocsStateRel + "/hashes"
	// HashesRel is the hash store itself.
	HashesRel = HashesDirRel + "/hashes.json"
	// DataRel is where a sandboxed gen-data script writes its output.
	DataRel = DocsStateRel + "/data"
	// OutputRel is the built site.
	OutputRel = DocsCacheRel + "/build"
	// VersionsRel holds one extracted checkout per archived version.
	VersionsRel = DocsCacheRel + "/versions"
)

// The declared values of the config keys that name a layout directory. A
// project that declares nothing gets these, and a project that declares
// something else has to keep it under [Root].
const (
	DocsDefault   = DocsRel + "/"
	OutputDefault = OutputRel + "/"
	PostsDefault  = PostsRel + "/"
)

// Directory is one function directory selfdoc claims: what it is for, which
// side of the authorship line it sits on, whether the repository commits it,
// and the paths it replaced.
type Directory struct {
	// Name is the directory's name under [Root].
	Name string
	// Side is whether people or selfdoc write its contents.
	Side Side
	// Commitment is whether the repository carries its contents.
	Commitment Commitment
	// Description says what the directory holds.
	Description string
	// DeprecatedNames are the paths this directory replaced, as they were
	// spelled relative to the repository root. A repository that still has
	// one of them is refused.
	DeprecatedNames []string
}

// declared is the whole claim, in the order a dump prints it.
var declared = []Directory{
	{
		Name:            DocsName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The pages a person writes, the underscore-prefixed templates they include, and the docs configuration that sits beside them.",
		DeprecatedNames: []string{"docs/"},
	},
	{
		Name:            DocsStateName,
		Side:            Generated,
		Commitment:      Committed,
		Description:     "What selfdoc generates and the repository keeps: the manifests, the hash baselines, the post revisions, the generated data files, and the generated pages.",
		DeprecatedNames: []string{".selfdoc/"},
	},
	{
		Name:            DocsCacheName,
		Side:            Generated,
		Commitment:      Uncommitted,
		Description:     "What selfdoc generates and the repository throws away: the built site and one extracted checkout per archived version.",
		DeprecatedNames: []string{"docs/_build/", ".selfdoc/cache/"},
	},
	{
		Name:            PostsName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The project's blog posts.",
		DeprecatedNames: []string{".selfdoc/posts/"},
	},
	{
		Name:            VocabularyName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The project's accepted and rejected vocabulary, read by the spell check and the glossary.",
		DeprecatedNames: nil,
	},
}

// Declared returns the directories selfdoc claims, in declaration order.
func Declared() []Directory {
	out := make([]Directory, len(declared))
	copy(out, declared)
	return out
}

// Lookup returns the declaration of one claimed directory.
func Lookup(name string) (Directory, bool) {
	for _, dir := range declared {
		if dir.Name == name {
			return dir, true
		}
	}
	return Directory{}, false
}

// Path joins a repository root with one of this package's slash-form relative
// paths, in the operating system's own spelling.
func Path(baseDir, rel string) string {
	return filepath.Join(baseDir, filepath.FromSlash(rel))
}

// UnderRoot reports whether a declared path names something inside [Root].
// A project may spell its docs and output paths as it likes as long as they
// live in the layout.
func UnderRoot(declaredPath string) bool {
	clean := path.Clean(strings.TrimRight(filepath.ToSlash(declaredPath), "/"))
	return clean == Root || strings.HasPrefix(clean, Root+"/")
}

// FunctionOf returns the function directory a relative path sits in.
func FunctionOf(rel string) (string, bool) {
	clean := strings.TrimRight(filepath.ToSlash(rel), "/")
	if !strings.HasPrefix(clean, Root+"/") {
		return "", false
	}
	rest := strings.TrimPrefix(clean, Root+"/")
	if rest == "" {
		return "", false
	}
	return strings.SplitN(rest, "/", 2)[0], true
}

// DirectoryManifestRel is a directory's ownership manifest, as a path relative
// to the repository root, in slash form.
func DirectoryManifestRel(name string) string {
	return Root + "/" + name + "/" + ManifestFileName
}

// DirectoryManifestPath is where a directory's ownership manifest sits, in the
// operating system's own spelling.
func DirectoryManifestPath(baseDir, name string) string {
	return Path(baseDir, DirectoryManifestRel(name))
}

// DirectoryManifestContent renders the manifest that declares one tool the
// owner of a directory. Every refusal that asks for a manifest prints from
// here, so the text a person is told to write is generated from the
// declaration rather than typed beside it.
func DirectoryManifestContent(owner string) string {
	return OwnerKey + " = " + strconv.Quote(owner) + "\n"
}

// ReadDirectoryManifest reads and validates one directory's ownership
// manifest.
//
// strictspec is the boundary validator: the file is checked against
// .strictspec/directory-manifest.schema.toml by the generated validator in
// this package, so a manifest that reaches a caller declares an owner and
// nothing else. A missing manifest is returned as the underlying
// [os.ErrNotExist], which callers answer with the file to create.
//
// The schema's format-version gate is supplied here rather than written into
// the file, the way a frontmatter block's is: a manifest on disk is the one
// [OwnerKey] line, and a file that declares the gate itself is refused, so the
// key has exactly one author.
func ReadDirectoryManifest(baseDir, name string) (*DirectoryManifest, error) {
	manifestPath := DirectoryManifestPath(baseDir, name)
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, err
	}
	if declaresFormatVersion(string(raw)) {
		return nil, fmt.Errorf(
			"%s declares %q, which the reader supplies: remove it, so the manifest is the one %s line",
			manifestPath, formatVersionKey, OwnerKey)
	}
	augmented := string(raw)
	if augmented != "" && !strings.HasSuffix(augmented, "\n") {
		augmented += "\n"
	}
	augmented += fmt.Sprintf("%s = %d\n", formatVersionKey, manifestFormatVersion)
	document, diags := ValidateBytes([]byte(augmented), "toml")
	if len(diags) > 0 {
		var detail strings.Builder
		for _, diagnostic := range diags {
			fmt.Fprintf(&detail, "\n  %s: %s [%s]",
				diagnostic.Path, diagnostic.Message, diagnostic.Code)
		}
		return nil, fmt.Errorf(
			"%s is not a valid ownership manifest. It declares %s and nothing else:%s",
			manifestPath, OwnerKey, detail.String())
	}
	return document, nil
}

// declaresFormatVersion reports whether a manifest's own text assigns the gate
// key that [ReadDirectoryManifest] supplies.
func declaresFormatVersion(text string) bool {
	for _, line := range strings.Split(text, "\n") {
		rest, found := strings.CutPrefix(strings.TrimSpace(line), formatVersionKey)
		if found && strings.HasPrefix(strings.TrimSpace(rest), "=") {
			return true
		}
	}
	return false
}

// KnownOwner reports whether a manifest names a tool this machine has: selfdoc
// itself, or any name PATH answers with an executable.
func KnownOwner(owner string) bool {
	if owner == Owner {
		return true
	}
	_, err := exec.LookPath(owner)
	return err == nil
}

// EnsureOwned answers whether selfdoc may write into one of the directories
// under [Root] in this repository.
//
// The manifest is the permission. A directory carrying none, or one naming
// another tool, is refused -- the first with the file and the line to write,
// which selfdoc never writes itself.
func EnsureOwned(baseDir, name string) error {
	manifest, err := ReadDirectoryManifest(baseDir, name)
	if errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf(
			"selfdoc may not write into %s: it carries no %s, and the manifest is the permission. selfdoc never writes one. Create %s holding this line:\n%s",
			filepath.Join(Root, name), ManifestFileName, DirectoryManifestRel(name),
			strings.TrimRight(DirectoryManifestContent(Owner), "\n"))
	}
	if err != nil {
		return err
	}
	if manifest.Owner != Owner {
		return fmt.Errorf(
			"selfdoc may not write into %s: %s declares %q as its owner, not %q",
			filepath.Join(Root, name), DirectoryManifestRel(name), manifest.Owner, Owner)
	}
	return nil
}

// EnsureDir creates a directory inside one of selfdoc's function directories,
// after checking the manifest that permits it, and refreshes the derived
// ignore file.
//
// rel is one of this package's slash-form relative paths. Creating anything
// under [Root] goes through here, so no path can reach the filesystem without
// its owning manifest having been read.
func EnsureDir(h *effects.Handle, baseDir, rel string) error {
	name, ok := FunctionOf(rel)
	if !ok {
		return fmt.Errorf("%q is not a path under %s", rel, Root)
	}
	if _, claimed := Lookup(name); !claimed {
		return fmt.Errorf("selfdoc does not claim %s", filepath.Join(Root, name))
	}
	if err := EnsureOwned(baseDir, name); err != nil {
		return err
	}
	if err := h.MkdirAll(Path(baseDir, rel)); err != nil {
		return err
	}
	return WriteIgnore(h, baseDir)
}

// The comments selfdoc's block of the derived ignore file sits between. Lines
// outside them belong to other tools and are left as they stand.
const (
	ignoreBegin = "# BEGIN selfdoc -- derived from selfdoc's layout declaration"
	ignoreEnd   = "# END selfdoc"
)

// IgnoreBlock is selfdoc's block of the derived ignore file: the marker
// comments around the lines that keep each uncommitted directory it owns out
// of the repository.
//
// An uncommitted directory contributes two lines rather than one. Its contents
// are ignored, and its [ManifestFileName] is not: the manifest is the
// permission to write into the directory, and a permission that git did not
// carry would have to be written again in every fresh checkout -- including
// the ones a multi-version build extracts out of git tags.
func IgnoreBlock() []string {
	block := []string{ignoreBegin}
	for _, dir := range declared {
		if dir.Commitment == Uncommitted {
			block = append(block,
				dir.Name+"/*",
				"!"+dir.Name+"/"+ManifestFileName)
		}
	}
	return append(block, ignoreEnd)
}

// RenderIgnore returns what the derived ignore file should hold, given what it
// holds now: selfdoc's block replaced in place, or appended when the file
// carries none, with every other line untouched.
func RenderIgnore(existing string) string {
	block := IgnoreBlock()
	var before, after []string
	inBlock, sawBlock := false, false
	for _, line := range strings.Split(strings.ReplaceAll(existing, "\r\n", "\n"), "\n") {
		switch {
		case strings.TrimSpace(line) == ignoreBegin:
			inBlock, sawBlock = true, true
		case strings.TrimSpace(line) == ignoreEnd:
			inBlock = false
		case inBlock:
			// A line inside selfdoc's own block is replaced by the block.
		case sawBlock:
			after = append(after, line)
		default:
			before = append(before, line)
		}
	}
	lines := append([]string{}, trimBlankEdges(before)...)
	if len(lines) > 0 {
		lines = append(lines, "")
	}
	lines = append(lines, block...)
	if rest := trimBlankEdges(after); len(rest) > 0 {
		lines = append(lines, "")
		lines = append(lines, rest...)
	}
	return strings.Join(lines, "\n") + "\n"
}

// trimBlankEdges drops the blank lines at both ends of a slice, so joining
// sections never doubles a blank line.
func trimBlankEdges(lines []string) []string {
	start, end := 0, len(lines)
	for start < end && strings.TrimSpace(lines[start]) == "" {
		start++
	}
	for end > start && strings.TrimSpace(lines[end-1]) == "" {
		end--
	}
	return lines[start:end]
}

// IgnorePath is where the derived ignore file sits.
func IgnorePath(baseDir string) string {
	return Path(baseDir, Root+"/"+IgnoreFileName)
}

// WriteIgnore brings the derived ignore file up to date, writing nothing when
// it already holds what it should.
func WriteIgnore(h *effects.Handle, baseDir string) error {
	target := IgnorePath(baseDir)
	existing, err := os.ReadFile(target)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	wanted := RenderIgnore(string(existing))
	if string(existing) == wanted {
		return nil
	}
	return h.AtomicWrite(target, []byte(wanted), effects.ModeDefault)
}

// IgnoreIsCurrent reports whether the derived ignore file holds selfdoc's block
// as declared, and returns the content it should hold.
func IgnoreIsCurrent(baseDir string) (bool, string) {
	existing, err := os.ReadFile(IgnorePath(baseDir))
	if err != nil {
		existing = nil
	}
	wanted := RenderIgnore(string(existing))
	return string(existing) == wanted, wanted
}
