// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.4.0
// schema:              selfdoc-directory-manifest (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package layout

import "github.com/stricttools/strictspec/go/strictspec"

// GENERATED_BY is the strictspec release that produced this file. It is
// INFORMATIONAL: pairing is on GENERATED_CODE_FORMAT below, so a later release
// of the runtime reads this file unchanged, and no tool may derive a dependency
// floor from this string.
const GENERATED_BY = "0.4.0"

// GENERATED_CODE_FORMAT is the shape of generated code this file was written
// to. The runtime pairing guard hard-errors unless this format is one the
// linked runtime reads; the remedy is regeneration.
const GENERATED_CODE_FORMAT = 2

// SCHEMA_FORMAT_VERSION is the document format_version this validator accepts.
const SCHEMA_FORMAT_VERSION = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"directory-manifest.schema.toml": `# strictspec schema -- the manifest that declares who owns one directory under
# a repository's stricttools/ root.
#
# Governs stricttools/<directory>/manifest.toml: the one-key document that
# says which tool owns the directory it sits in. The generated validator
# (internal/layout/selfdoc_directory_manifest_gen.go) is what
# layout.ReadDirectoryManifest validates each file against, so a manifest that reaches the permission check
# or the layout validation has already been through here.
#
# THE KEY REGISTRY. "owner" is the whole set of keys a manifest FILE may carry:
# a record is closed, so a key that is not declared here is refused rather than
# silently ignored.
#
# THE READER-SUPPLIED TRAILER. "format_version" is not written by the person
# who writes a manifest: layout.ReadDirectoryManifest appends it to the file's
# bytes before validating, and refuses a file that declares it, so the key has
# exactly one author. A manifest on disk is therefore one line long.
#
# SCOPE (honest subset): this schema owns the file's raw DOCUMENT SHAPE -- the
# key registry and the owner value's lexeme class. It does not own whether the
# named owner is a tool this machine has, whether selfdoc's own claim on the
# directory agrees with it, or whether the directory the manifest sits in
# exists at all; those are selfdoc-native checks over the tree rather than over
# one document.

name = "selfdoc-directory-manifest"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "DirectoryManifest"
description = "One directory's ownership manifest under a repository's stricttools/ root: the single key naming the tool that owns the directory."

[types.DirectoryManifest]
type = "record"
description = "The manifest file a directory under stricttools/ carries."

[types.DirectoryManifest.fields.format_version]
type = "integer"
required = true
description = "Document format-version gate. v1 manifests carry 1. Supplied by the reader, never written into the file."

[types.DirectoryManifest.fields.owner]
type = "string"
required = true
non_empty = true
description = "The tool that owns this directory. Only the owner creates the directory and decides whether what is written into it is acceptable; reading and writing are open to anyone."
`,
}

const embeddedMainFile = "directory-manifest.schema.toml"

var program *strictspec.Program

func init() {
	// Pairing: this file's generated-code format must be one the runtime reads.
	strictspec.RequireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*DirectoryManifest, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindDirectoryManifest(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*DirectoryManifest, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindDirectoryManifest(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*DirectoryManifest, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindDirectoryManifest(v), nil
}

// DirectoryManifest is the frozen typed binding of the "DirectoryManifest" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type DirectoryManifest struct {
	FormatVersion int64
	Owner         string
}

func bindDirectoryManifest(v strictspec.Value) *DirectoryManifest {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &DirectoryManifest{}
	if fv, ok := v.Field("format_version"); ok {
		out.FormatVersion = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("owner"); ok {
		out.Owner = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithFormatVersion returns a copy of DirectoryManifest with FormatVersion set to the given value.
func (x *DirectoryManifest) WithFormatVersion(v int64) *DirectoryManifest {
	c := *x
	c.FormatVersion = v
	return &c
}

// WithOwner returns a copy of DirectoryManifest with Owner set to the given value.
func (x *DirectoryManifest) WithOwner(v string) *DirectoryManifest {
	c := *x
	c.Owner = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
