// Package spelling is the spelling engine: one word checker serving every
// surface that needs one.
//
// The check command runs it over a project's docs and posts (SPELL001), and
// the spell-corpus command runs the same engine over every sibling project on
// the machine. There is one engine and one accept list; a surface that wants
// spelling asks this package, and no surface carries a second opinion about
// what a word is.
//
// # Vendored word list and its licence obligations
//
// The acceptance oracle is a pinned snapshot of the English Speller Database
// (ESDB, formerly SCOWL), generated from https://app.aspell.net/create at size
// 70 with US, British (-ise and -ize) and Canadian spellings. It is embedded
// from wordlist/:
//
//   - words.txt -- the words.
//   - COPYRIGHT.txt -- upstream's copyright file, verbatim.
//   - SOURCE.json -- the retrieval record (URL, every parameter, upstream git
//     revisions, SHA-256, word count), regenerated by the wordlist
//     regeneration script.
//
// Upstream's grant permits use, copying, modification, distribution and sale of
// word lists created from the database "provided that the above copyright
// notice appears in all copies and that both the above copyright notice and
// this notice appear in supporting documentation". Shipping COPYRIGHT.txt
// verbatim beside the words is what satisfies that, and it carries the
// sub-source notices upstream attaches -- the UK Advanced Cryptics Dictionary
// notice in particular, whose own terms require that it "be prominently
// displayed and the text of this document must be included verbatim". Never
// ship words.txt without COPYRIGHT.txt; never edit either by hand.
//
// Two candidates were rejected before this one. A widely-used word-frequency
// corpus carries a share-alike condition on its data, which would reach the
// package that redistributes it. The largest public-domain English list is an
// unfiltered scrape: it accepts enough garbage to be worthless as an
// acceptance oracle, which is the one job here.
//
// # The accept list
//
// Genuine terms the general English list cannot know -- project names, tool
// names, technical vocabulary -- live in a single plain-text file at
// [AcceptListPath] (~/Projects/ark/spelling-accept.txt). One word per line,
// "#" starts a comment, and a word on the list is accepted everywhere,
// permanently.
//
// That location is outside every repository, so the list has no version
// history and no backup. This was chosen deliberately: the list is
// cross-project by nature and belongs to the machine rather than to any one
// repo, and losing it costs a re-triage, not correctness.
//
// A missing file means an empty list, not an error. A fresh machine has simply
// never accepted anything yet; that is genuine absence, not a degraded mode,
// and the check behaves identically before and after the file appears -- it
// just has fewer accepted terms. A file that exists and is malformed is a hard
// error: it was written by someone who meant something by it, and guessing at
// their intent would silently drop accepted terms.
//
// # The renderer vocabulary
//
// The accept list cannot carry a word selfdoc itself writes. selfdoc renders
// reference pages into a consumer's docs tree and then spell-checks them, so a
// heading a renderer invents becomes an error-severity lint in that consumer's
// project -- text they did not write, on a page they cannot edit, against a
// machine list they should not have to populate. Fixed renderer vocabulary is
// therefore carried by the engine, in [RendererVocabulary], and consulted on
// every run regardless of what the machine has accepted.
package spelling

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/stricttools/selfdoc/internal/directives"
	"github.com/stricttools/selfdoc/internal/tokenizer"
	"github.com/stricttools/selfdoc/internal/util"
)

// wordlistFS carries the vendored word list, its retrieval record and
// upstream's copyright notice. All three travel together because the licence
// conditions redistribution of the words on the notice accompanying them.
//
//go:embed wordlist/words.txt wordlist/SOURCE.json wordlist/COPYRIGHT.txt
var wordlistFS embed.FS

// acceptListFilename is the name of the one shared accept list.
const acceptListFilename = "spelling-accept.txt"

// Lookup answers whether a vocabulary accepts a word as written.
//
// It exists so a check run can consult the vendored list, the renderer
// vocabulary and the accept list as one vocabulary without copying 170,000
// entries into a fresh map per document. [Vocab] satisfies it, so every call
// site that holds one set passes it directly.
type Lookup interface {
	// Has reports whether the vocabulary carries word, spelled as given.
	Has(word string) bool
}

// Vocab is a set of words, the Go counterpart of the frozensets the Python
// surface passed around.
type Vocab map[string]struct{}

// Has reports whether the set carries word, spelled as given.
func (v Vocab) Has(word string) bool {
	_, ok := v[word]
	return ok
}

// layered is a Lookup over several vocabularies, consulted in order. It stands
// in for the set unions the Python built per call, without their copy.
type layered []Lookup

// Has reports whether any layer carries word.
func (l layered) Has(word string) bool {
	for _, vocab := range l {
		if vocab != nil && vocab.Has(word) {
			return true
		}
	}
	return false
}

// AcceptListError reports that the accept list exists but cannot be read as
// written.
//
// It is never returned for a missing file -- absence is an empty list. It is
// returned for a line the format does not admit, naming the file, the line
// number and what was wrong with it.
type AcceptListError struct {
	// Message is the whole diagnostic, already naming file and line.
	Message string
}

// Error renders the diagnostic.
func (e *AcceptListError) Error() string { return e.Message }

// Misspelling is one unrecognized word, located precisely enough to open and
// fix.
type Misspelling struct {
	// File is the path named in the diagnostic, as the caller gave it.
	File string
	// Line is the 1-based line the word sits on.
	Line int
	// Column is the 1-based character column in the raw source line.
	Column int
	// Word is the unrecognized word as written.
	Word string
	// Suggestions are the edit-distance-1 neighbours, empty when none were
	// asked for or none were found.
	Suggestions []string
}

// Describe renders the diagnostic message a lint carries.
func (m Misspelling) Describe() string {
	text := fmt.Sprintf("Unrecognized word '%s' (col %d)", m.Word, m.Column)
	if len(m.Suggestions) > 0 {
		text += "; did you mean " + strings.Join(m.Suggestions, ", ") + "?"
	}
	return text
}

// UnknownWord is one unrecognized word located in a single source line.
type UnknownWord struct {
	// Column is the 0-based character offset of the word in the raw line.
	Column int
	// Word is the unrecognized word as written.
	Word string
}

// -- The vocabulary ---------------------------------------------------------

// loadWordlist reads the vendored ESDB word list, exactly as vendored.
var loadWordlist = sync.OnceValue(func() Vocab {
	raw, err := wordlistFS.ReadFile("wordlist/words.txt")
	if err != nil {
		// The file is embedded, so a read failure is a build defect rather
		// than a runtime condition a caller could act on.
		panic("spelling: embedded word list is unreadable: " + err.Error())
	}
	words := Vocab{}
	for _, line := range strings.Split(string(raw), "\n") {
		if line == "" {
			continue
		}
		words[line] = struct{}{}
	}
	return words
})

// LoadWordlist returns the vendored ESDB word list, exactly as vendored.
//
// The list is read and indexed once per process; every later call returns the
// same set.
func LoadWordlist() Vocab { return loadWordlist() }

// WordlistBytes returns the vendored word list's raw bytes, as vendored.
//
// The digest and word count SOURCE.json records describe these bytes, so a
// caller verifying the retrieval record measures what actually ships.
func WordlistBytes() []byte {
	raw, err := wordlistFS.ReadFile("wordlist/words.txt")
	if err != nil {
		panic("spelling: embedded word list is unreadable: " + err.Error())
	}
	return raw
}

// wordlistSource parses the vendored word list's retrieval record.
var wordlistSource = sync.OnceValues(func() (map[string]any, error) {
	raw, err := wordlistFS.ReadFile("wordlist/SOURCE.json")
	if err != nil {
		return nil, err
	}
	var record map[string]any
	if err := json.Unmarshal(raw, &record); err != nil {
		return nil, err
	}
	return record, nil
})

// WordlistSource returns the vendored word list's retrieval record: the URL,
// every generator parameter, the upstream git revisions, the digest and the
// word count.
func WordlistSource() (map[string]any, error) { return wordlistSource() }

// WordlistCopyright returns upstream's copyright notice, verbatim, for
// display. Shipping it beside the words is what the licence conditions
// redistribution on.
func WordlistCopyright() string {
	raw, err := wordlistFS.ReadFile("wordlist/COPYRIGHT.txt")
	if err != nil {
		panic("spelling: embedded copyright notice is unreadable: " + err.Error())
	}
	return string(raw)
}

// AcceptListPath returns the one accept list's path,
// ~/Projects/ark/spelling-accept.txt.
//
// The home directory is resolved per call rather than once at load, so a
// process that changes HOME -- an isolated test run, a sandboxed corpus sweep
// -- reads the list its own environment names.
func AcceptListPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		// With no home directory there is no shared list; the relative path
		// then simply does not exist, which is an empty accept list.
		return filepath.Join("Projects", "ark", acceptListFilename)
	}
	return filepath.Join(home, "Projects", "ark", acceptListFilename)
}

// acceptEntryRe is the grammar of an accept-list entry: a single word,
// letters, with apostrophes allowed inside contractions and possessives.
// Nothing else, because nothing else could ever be consulted -- the checker
// splits hyphenated compounds into their parts and skips any token carrying a
// digit, so a hyphenated or numeric entry would sit on the list accepting
// nothing.
var acceptEntryRe = regexp.MustCompile(`^` + letterClass + `+(?:['’]` + letterClass + `+)*$`)

// LoadAcceptList reads the accept list at path, or the one [AcceptListPath]
// names when path is empty.
//
// A file that does not exist is an empty list, not an error: a fresh machine
// has simply accepted nothing yet. A file that exists and carries a line the
// format does not admit is an [AcceptListError] naming the line number and the
// reason.
func LoadAcceptList(path string) (Vocab, error) {
	target := path
	if target == "" {
		target = AcceptListPath()
	}
	info, err := os.Stat(target)
	if err != nil || !info.Mode().IsRegular() {
		return Vocab{}, nil
	}
	raw, err := os.ReadFile(target)
	if err != nil {
		return nil, &AcceptListError{
			Message: fmt.Sprintf("%s: %s", target, err),
		}
	}
	accepted := Vocab{}
	for index, line := range strings.Split(string(raw), "\n") {
		entry := strings.TrimSpace(strings.SplitN(line, "#", 2)[0])
		if entry == "" {
			continue
		}
		if !acceptEntryRe.MatchString(entry) {
			return nil, &AcceptListError{Message: fmt.Sprintf(
				"%s:%d: %s is not a single word. An accept-list line holds "+
					"one word (letters, with apostrophes allowed inside it) "+
					"or a '#' comment. Split a hyphenated compound into its "+
					"parts and give each its own line -- the checker checks "+
					"the parts, so a hyphenated entry would accept nothing.",
				target, index+1, util.PythonRepr(entry),
			)}
		}
		accepted[entry] = struct{}{}
	}
	return accepted, nil
}

// -- The renderer vocabulary ------------------------------------------------

// RendererVocabulary is the fixed vocabulary selfdoc's own renderers write
// into generated pages.
//
// A generated page is checked by the same SPELL001 that checks an authored
// one, so a heading, a column header or a type word a renderer invents is
// judged against this engine in every project that renders one. The consumer
// cannot fix such a finding: the text is not theirs, and the accept list that
// could silence it belongs to one machine while the rendered page ships
// everywhere. Fixed renderer vocabulary is therefore carried by the engine
// itself and accepted unconditionally, on every machine, with or without an
// accept list.
//
// Seeded from the strictcli reference renderer: the "Clearable" heading a
// sparse update publishes its unset tokens under, the "Env" column of the flag
// table, the "Config" rows of the configuration table, the type words the Type
// column renders, and the two tool names its prose names. A renderer that adds
// a word adds it here; the strictcli-support tests render a schema exercising
// every construct and fail when one is missing.
var RendererVocabulary = Vocab{
	// Literal headings and labels.
	"clearable": {},
	"config":    {},
	"env":       {},
	// The type words a value schema renders as, as one family.
	"str":   {},
	"bool":  {},
	"int":   {},
	"float": {},
	"list":  {},
	"dict":  {},
	// Tool names the renderer's own prose names.
	"selfdoc":   {},
	"strictcli": {},
}

// -- Word scanning ----------------------------------------------------------

// letterClass is the character class Python spells `[^\W\d_]`: a word
// character that is neither a decimal digit nor an underscore.
//
// Python's `\w` is every character str.isalnum accepts plus the underscore,
// and `\d` is the decimal digits alone, so subtracting them leaves the
// letters together with the letterlike and other numerals -- Nl and No. A
// superscript two is No, which is why "m²" is one word rather than the word
// "m" beside a character no pattern claims.
const letterClass = `[\p{L}\p{Nl}\p{No}]`

// spaceClass and nonSpaceClass are this package's short spellings of Python's
// Unicode-aware `\s` and `\S`, which Go's own `\s` does not reproduce:
// Python's class carries the C0 separators, the next-line control, and every
// Unicode separator category.
const (
	spaceClass    = util.PythonSpaceClass
	nonSpaceClass = util.PythonNonSpaceClass
)

// attrTokenClass is the character class Python spells `[\w-]`: a Unicode word
// character or a hyphen. Go's own `\w` is ASCII-only, so the class is spelled
// out.
const attrTokenClass = `[\p{L}\p{N}_-]`

// mask is one Markdown or HTML construct whose content is never prose. Each is
// blanked with same-length spaces so every surviving byte keeps its offset,
// and therefore every surviving character keeps its column.
type mask struct {
	// pattern matches the construct.
	pattern *regexp.Regexp
	// wordBoundary is set for a pattern Python anchored with a leading `\b`,
	// which RE2 cannot express Unicode-aware. Such a pattern is anchored at
	// the position being tried and the boundary is checked by hand, retrying
	// one character later on a rejection -- what the regex engine does when a
	// match fails its leading assertion.
	wordBoundary bool
}

// masks are applied in order; each runs over what the previous ones left, so
// the order is part of the behavior.
var masks = []mask{
	// Link and image destinations: the text stays, the URL goes.
	{pattern: regexp.MustCompile(`\]\([^)\n]*\)`)},
	// Reference-style link labels and link-reference definitions.
	{pattern: regexp.MustCompile(`\]\[[^\]\n]*\]`)},
	{pattern: regexp.MustCompile(`(?m)^` + spaceClass + `*\[[^\]\n]+\]:` + spaceClass + `*` + nonSpaceClass + `+`)},
	// HTML tags, comments and autolinks. A tag's attributes are inside it, so
	// the pattern has to admit whitespace -- an earlier form stopped at the
	// first space and let the element name and every attribute value through
	// as prose. The opening character still has to look like the start of a
	// tag (a name, a closing slash, or a "!" declaration), which keeps a
	// comparison written in prose ("x < y and z > 0") out of it. A tag broken
	// across lines is not covered: the scanner is handed one raw source line
	// at a time, so the columns it reports stay true.
	{pattern: regexp.MustCompile(`</?[A-Za-z!][^<>]*>`)},
	// HTML entity references, named and numeric. An entity is markup that
	// renders as one character, so its name is no more a word than a tag's is
	// -- "&nbsp;" is a space, not the word "nbsp".
	{pattern: regexp.MustCompile(`&(?:[A-Za-z][A-Za-z0-9]*|#\p{Nd}+|#[xX][0-9A-Fa-f]+);`)},
	// Bare URLs and mail addresses left loose in prose.
	{pattern: regexp.MustCompile(`^[a-z][a-z0-9+.-]*://` + nonSpaceClass + `+`), wordBoundary: true},
	{pattern: regexp.MustCompile(`^mailto:` + nonSpaceClass + `+`), wordBoundary: true},
	// Directive markers. The inline ":-:" marker and its attributes live
	// inside a paragraph; the block forms are handled by blankBlockMarkers,
	// whose Python spelling used a lookahead RE2 cannot express.
	{pattern: regexp.MustCompile(`:-:` + spaceClass + `+` + attrTokenClass + `+` +
		`(?:` + spaceClass + `+` + attrTokenClass + `+="[^"\n]*")*`)},
}

// blockMarkers are the directive markers that stand alone on a line. Python
// matched them with `^(?::-:|:<:|:@:|:=:|:::|:>:)(?=\s|$)` under MULTILINE.
var blockMarkers = []string{":-:", ":<:", ":@:", ":=:", ":::", ":>:"}

// machineChunkRe matches a whitespace-delimited chunk that is a machine token
// -- an identifier, a path, a version, a qualified name -- rather than
// English. The whole chunk is skipped rather than picked apart, because the
// letters in "os.path" and "max_size" are not words anyone can misspell.
var machineChunkRe = regexp.MustCompile(
	`[0-9_/\\@~^$*]` + // digits and the punctuation identifiers use
		`|::` + // namespace separators
		`|` + letterClass + `\.` + letterClass, // a dot joining two letters
)

// wordRe matches a word: letters, with apostrophes allowed inside and one
// allowed at the end (a plural possessive). Hyphens are separators, not part
// of a word, so a hyphenated compound arrives here already split into parts.
var wordRe = regexp.MustCompile(letterClass + `+(?:['’]` + letterClass + `+)*['’]?`)

// chunkRe splits a masked line into its whitespace-delimited chunks.
var chunkRe = regexp.MustCompile(nonSpaceClass + `+`)

// innerCapitalRe matches an internal case change, which marks camelCase or
// PascalCase: an identifier spelled into prose without backticks. Such a token
// is skipped, because the alternative is flagging every unbackticked symbol
// name in the fleet's documentation.
//
// Two shapes, because a case change has two directions. A capital after a
// lowercase letter is the familiar one ("parseFrontmatter", "TextResponse").
// The other is a run of capitals ending against a capitalized word --
// "JSONResponse", "XMLHttpRequest", "IOError" -- where the acronym and the
// word meet capital-to-capital and there is no lowercase letter before the
// boundary at all. Requiring two capitals in the run keeps an ordinary
// capitalized word out: "Adress" starting a sentence is still a misspelling to
// report.
var innerCapitalRe = regexp.MustCompile(`[a-z][A-Z]|[A-Z]{2}[a-z]`)

// alphabet is the letter set edit-distance-1 candidates are generated over.
const alphabet = "abcdefghijklmnopqrstuvwxyz"

// blank blanks every non-prose construct in line, preserving its byte length
// and therefore every surviving character's column.
func blank(line string) string {
	masked := directives.BlankBacktickSpans(line)
	for _, m := range masks {
		if m.wordBoundary {
			masked = blankBoundaryMatches(masked, m.pattern)
			continue
		}
		masked = blankMatches(masked, m.pattern)
	}
	return blankBlockMarkers(masked)
}

// blankMatches replaces every match of pattern with one space per byte.
func blankMatches(text string, pattern *regexp.Regexp) string {
	locations := pattern.FindAllStringIndex(text, -1)
	if locations == nil {
		return text
	}
	buffer := []byte(text)
	for _, location := range locations {
		blankRange(buffer, location[0], location[1])
	}
	return string(buffer)
}

// blankBoundaryMatches blanks every match of pattern that begins at a word
// boundary, where pattern is anchored at the start of the text it is given.
//
// A match whose preceding character is a word character is rejected and the
// scan retries one character later, which is what a regex engine does when a
// leading `\b` fails: it advances its start position rather than skipping past
// the whole candidate.
func blankBoundaryMatches(text string, pattern *regexp.Regexp) string {
	buffer := []byte(text)
	position := 0
	for position < len(text) {
		location := pattern.FindStringIndex(text[position:])
		if location == nil {
			// Anchored, so no match here means none starting here; step one
			// character on and try again.
			_, width := utf8.DecodeRuneInString(text[position:])
			position += width
			continue
		}
		start, end := position+location[0], position+location[1]
		if wordBoundaryAt(text, start) {
			blankRange(buffer, start, end)
			position = end
			continue
		}
		_, width := utf8.DecodeRuneInString(text[start:])
		position = start + width
	}
	return string(buffer)
}

// wordBoundaryAt reports whether offset in text sits on a word boundary,
// given that the character at offset is itself a word character.
func wordBoundaryAt(text string, offset int) bool {
	if offset == 0 {
		return true
	}
	previous, _ := utf8.DecodeLastRuneInString(text[:offset])
	return !isWordRune(previous)
}

// isWordRune reports whether r is a word character under Python's Unicode
// `\w`: a letter, a number of any kind, or an underscore.
func isWordRune(r rune) bool {
	return r == '_' || unicode.IsLetter(r) || unicode.IsNumber(r)
}

// blankBlockMarkers blanks a directive marker standing at the start of a line
// and followed by whitespace or the end of the text.
func blankBlockMarkers(text string) string {
	buffer := []byte(text)
	for start := 0; start <= len(text); {
		for _, marker := range blockMarkers {
			if !strings.HasPrefix(text[start:], marker) {
				continue
			}
			after := start + len(marker)
			next, _ := utf8.DecodeRuneInString(text[after:])
			if after == len(text) || util.IsPythonSpace(next) {
				blankRange(buffer, start, after)
			}
			break
		}
		newline := strings.IndexByte(text[start:], '\n')
		if newline < 0 {
			break
		}
		start += newline + 1
	}
	return string(buffer)
}

// blankRange overwrites buffer[start:end) with one space per byte.
func blankRange(buffer []byte, start, end int) {
	for i := start; i < end; i++ {
		buffer[i] = ' '
	}
}

// isKnown reports whether vocab holds word in a standard casing form.
//
// Exact first, so an acronym the list carries ("USA", "CPU") is accepted as
// written. Then lowercase, so a capitalized sentence start and an all-caps
// heading are accepted from the ordinary entry.
func isKnown(word string, vocab Lookup) bool {
	return vocab.Has(word) || vocab.Has(strings.ToLower(word))
}

// accepts reports whether word is spelled acceptably against vocab.
func accepts(word string, vocab Lookup) bool {
	if utf8.RuneCountInString(word) < 2 {
		// A lone letter is an enumeration marker or an initial, never a
		// misspelling anyone can act on.
		return true
	}
	if innerCapitalRe.MatchString(word) {
		return true
	}
	if isKnown(word, vocab) {
		return true
	}
	// Possessives: the list carries "dog's" but not every proper noun's.
	for _, suffix := range []string{"'s", "’s", "'", "’"} {
		if !strings.HasSuffix(word, suffix) {
			continue
		}
		base := strings.TrimSuffix(word, suffix)
		if base != "" && isKnown(base, vocab) {
			return true
		}
	}
	return false
}

// SuggestionsFor returns up to limit edit-distance-1 neighbours of word in
// vocab, sorted.
//
// Deliberately cheap: one edit, generated and looked up, no scoring model and
// no distance-2 search. A word with no neighbour gets no suggestion, which is
// a better answer than an expensive wrong one. A word over sixteen characters
// gets none either -- the candidate set grows with its length and the answer
// stops being worth generating.
func SuggestionsFor(word string, vocab Lookup, limit int) []string {
	lowered := strings.ToLower(word)
	runes := []rune(lowered)
	if len(runes) > 16 {
		return nil
	}
	candidates := map[string]struct{}{}
	for index := 0; index <= len(runes); index++ {
		left := string(runes[:index])
		right := runes[index:]
		if len(right) > 0 {
			candidates[left+string(right[1:])] = struct{}{} // delete
			if len(right) > 1 {
				swapped := append([]rune{right[1], right[0]}, right[2:]...)
				candidates[left+string(swapped)] = struct{}{} // swap
			}
			for _, letter := range alphabet {
				candidates[left+string(letter)+string(right[1:])] = struct{}{} // replace
			}
		}
		for _, letter := range alphabet {
			candidates[left+string(letter)+string(right)] = struct{}{} // insert
		}
	}
	delete(candidates, lowered)
	var hits []string
	for candidate := range candidates {
		if vocab.Has(candidate) {
			hits = append(hits, candidate)
		}
	}
	sort.Strings(hits)
	if len(hits) > limit {
		hits = hits[:limit]
	}
	return hits
}

// IterUnknownWords returns every unrecognized word in one raw source line,
// each with its 0-based character offset into that line.
//
// Markers, code spans, URLs and directive syntax are blanked before scanning,
// and machine tokens are skipped whole.
func IterUnknownWords(line string, vocab Lookup) []UnknownWord {
	masked := blank(line)
	var found []UnknownWord
	for _, chunkLocation := range chunkRe.FindAllStringIndex(masked, -1) {
		chunk := masked[chunkLocation[0]:chunkLocation[1]]
		if machineChunkRe.MatchString(chunk) {
			continue
		}
		base := chunkLocation[0]
		for _, wordLocation := range wordRe.FindAllStringIndex(chunk, -1) {
			word := chunk[wordLocation[0]:wordLocation[1]]
			if accepts(word, vocab) {
				continue
			}
			found = append(found, UnknownWord{
				// Blanking preserves byte offsets, so the offset addresses
				// the same byte in the original line; the column a reader
				// wants is that offset in characters.
				Column: utf8.RuneCountInString(line[:base+wordLocation[0]]),
				Word:   word,
			})
		}
	}
	return found
}

// CheckText spell-checks Markdown content, reporting file, line and column.
//
// Structure comes from the block tokenizer: only text-bearing tokens are
// scanned, so fenced code blocks and directive blocks are excluded by
// construction rather than by pattern-matching them back out. Within a token
// the RAW source lines are scanned, not the token's parsed text, so every
// reported column is a real column in the file.
//
// content is a Markdown body with its frontmatter already removed, and file is
// the path to name in each diagnostic. A nil vocab means the vendored word
// list; a nil accepted means the list [AcceptListPath] names, which is where
// the only error this can return comes from. lineOffset is added to every
// reported line, for a body whose frontmatter was stripped. suggest decides
// whether edit-distance-1 suggestions are computed.
//
// The renderer vocabulary is not optional and not machine-local: a page
// selfdoc rendered is checked on machines that have accepted nothing, so it is
// consulted on every run.
func CheckText(
	content string,
	file string,
	vocab Vocab,
	accepted Vocab,
	lineOffset int,
	suggest bool,
) ([]Misspelling, error) {
	words := Lookup(vocab)
	if vocab == nil {
		words = LoadWordlist()
	}
	accept := accepted
	if accepted == nil {
		loaded, err := LoadAcceptList("")
		if err != nil {
			return nil, err
		}
		accept = loaded
	}
	known := layered{words, RendererVocabulary}
	if len(accept) > 0 {
		known = append(known, accept)
	}

	lines := strings.Split(content, "\n")
	var results []Misspelling
	for _, token := range tokenizer.Tokenize(content) {
		if !tokenizer.IsTextBearing(token) {
			continue
		}
		for lineNumber := token.Start(); lineNumber <= token.End(); lineNumber++ {
			if lineNumber < 1 || lineNumber > len(lines) {
				continue
			}
			raw := lines[lineNumber-1]
			for _, unknown := range IterUnknownWords(raw, known) {
				var suggestions []string
				if suggest {
					suggestions = SuggestionsFor(unknown.Word, known, 3)
				}
				results = append(results, Misspelling{
					File:        file,
					Line:        lineNumber + lineOffset,
					Column:      unknown.Column + 1,
					Word:        unknown.Word,
					Suggestions: suggestions,
				})
			}
		}
	}
	return results, nil
}
