package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stricttools/selfdoc/internal/layout"
	"github.com/stricttools/selfdoc/internal/testproject"
)

// The _CLAUDE.md template generates .claude/CLAUDE.md. A repository whose
// CLAUDE.md an earlier selfdoc generated at its root moves it there through
// `selfdoc layout migrate`.

// claudeTemplate is the root-file template every fixture here declares.
const claudeTemplate = ".strictmetadata/docs/_CLAUDE.md"

// rootClaudeProject is a committed repository on the current layout whose
// CLAUDE.md sits at its root, generated by an earlier selfdoc, beside a
// committed .claude/settings.json.
func rootClaudeProject(t *testing.T) string {
	t.Helper()
	// No source, so the only page is the one written here, and check has
	// nothing to report but what this file is about.
	dir := testproject.Make(t, map[string]any{"root_files": []any{claudeTemplate}, "source": []any{}})
	testproject.WriteText(t, filepath.Join(testproject.DocsDir(dir), "index.md"),
		"+++\ntitle = \"Test Project\"\ndescription = \"The documentation of a test project whose agent instructions are generated from a template and committed where Claude Code reads them.\"\n+++\n\n# Test Project\n\nWelcome to the docs.\n")
	testproject.WriteText(t, filepath.Join(dir, filepath.FromSlash(claudeTemplate)), "# Agent notes\n")
	writeGeneratedRootClaude(t, dir, claudeTemplate)
	testproject.WriteText(t, filepath.Join(dir, ".claude", "settings.json"), "{}\n")
	testproject.Git(t, dir, "init", "-q")
	testproject.Git(t, dir, "add", ".")
	testproject.Git(t, dir, "commit", "-q", "-m", "a generated root CLAUDE.md")
	return dir
}

// writeGeneratedRootClaude writes CLAUDE.md at the repository root as a
// selfdoc of the previous release generated it from template: read-only,
// under the header naming the template.
func writeGeneratedRootClaude(t *testing.T, dir, template string) {
	t.Helper()
	path := filepath.Join(dir, "CLAUDE.md")
	testproject.WriteText(t, path, readmeHeader(template)+"\n\n# Agent notes\n")
	if err := os.Chmod(path, 0o444); err != nil {
		t.Fatal(err)
	}
}

// The whole path: gen refuses and check reports the root file, naming the
// move; the dry run prints it and changes nothing; the move commits it; gen
// then generates .claude/CLAUDE.md and check is clean.
func TestAGeneratedRootClaudeMovesUnderDotClaudeAndGenAndCheckClear(t *testing.T) {
	isolate(t)
	dir := rootClaudeProject(t)

	gen := run(t, dir, "gen", "--no-auto-commit")
	if gen.ExitCode == 0 || !strings.Contains(gen.Stderr, "'selfdoc layout migrate'") {
		t.Fatalf("gen exited %d without naming the move:\n%s", gen.ExitCode, gen.Stderr)
	}
	check := run(t, dir, "check", "--no-auto-commit")
	if check.ExitCode == 0 || !strings.Contains(check.Stdout+check.Stderr, "generated-claude-md-at-repository-root") {
		t.Fatalf("check exited %d without reporting the root file:\n%s\n%s", check.ExitCode, check.Stdout, check.Stderr)
	}

	before := treeListing(t, dir)
	dry := run(t, dir, "layout", "migrate", "--dry-run")
	if dry.ExitCode != 0 {
		t.Fatalf("the dry run failed:\n%s\n%s", dry.Stdout, dry.Stderr)
	}
	if !strings.Contains(dry.Stdout, "move CLAUDE.md -> .claude/CLAUDE.md") {
		t.Errorf("the plan does not carry the move:\n%s", dry.Stdout)
	}
	if after := treeListing(t, dir); after != before {
		t.Errorf("the dry run changed the tree:\nbefore:\n%s\nafter:\n%s", before, after)
	}

	migrate := run(t, dir, "layout", "migrate")
	if migrate.ExitCode != 0 {
		t.Fatalf("the move failed:\n%s\n%s", migrate.Stdout, migrate.Stderr)
	}
	if exists(filepath.Join(dir, "CLAUDE.md")) {
		t.Error("CLAUDE.md is still at the repository root")
	}
	moved := filepath.Join(dir, ".claude", "CLAUDE.md")
	if got := readText(t, moved); !strings.HasPrefix(got, readmeHeader(claudeTemplate)) {
		t.Errorf(".claude/CLAUDE.md holds:\n%s", got)
	}
	if info, err := os.Stat(moved); err != nil || info.Mode().Perm() != 0o444 {
		t.Errorf(".claude/CLAUDE.md: %v, %v; want mode 0444", info, err)
	}
	if status := gitOutput(t, dir, "status", "--porcelain", "--", "CLAUDE.md", ".claude"); status != "" {
		t.Errorf("the move left uncommitted changes:\n%s", status)
	}
	if subject := strings.TrimSpace(gitOutput(t, dir, "log", "-1", "--format=%s")); subject !=
		"selfdoc layout migrate: move the generated CLAUDE.md to .claude/CLAUDE.md" {
		t.Errorf("the last commit is %q", subject)
	}
	if tracked := strings.TrimSpace(gitOutput(t, dir, "ls-files", "CLAUDE.md", ".claude/CLAUDE.md")); tracked != ".claude/CLAUDE.md" {
		t.Errorf("git tracks %q", tracked)
	}

	if gen := run(t, dir, "gen", "--no-auto-commit"); gen.ExitCode != 0 {
		t.Fatalf("gen after the move failed:\n%s\n%s", gen.Stdout, gen.Stderr)
	}
	if got := readText(t, moved); !strings.Contains(got, "# Agent notes") {
		t.Errorf("gen did not regenerate .claude/CLAUDE.md:\n%s", got)
	}
	if exists(filepath.Join(dir, "CLAUDE.md")) {
		t.Error("gen wrote a CLAUDE.md at the repository root")
	}
	if check := run(t, dir, "check", "--no-auto-commit"); check.ExitCode != 0 {
		t.Errorf("check after the move exited %d:\n%s\n%s", check.ExitCode, check.Stdout, check.Stderr)
	}
	if result := run(t, dir, "layout", "migrate"); result.ExitCode == 0 ||
		!strings.Contains(result.Stderr, "Nothing to migrate") {
		t.Errorf("a second move: exit %d\n%s", result.ExitCode, result.Stderr)
	}
}

// A repository on a previous layout moves its directories and its generated
// CLAUDE.md in one migration, the header naming the template where it now is.
func TestMigrateOffThePreviousLayoutMovesTheGeneratedRootClaudeToo(t *testing.T) {
	isolate(t)
	dir := previousLayoutProject(t, false)
	oldTemplate := layout.EarlierRoot + "/docs/_CLAUDE.md"
	testproject.WriteJSON(t, filepath.Join(dir, "selfdoc.json"), testproject.DefaultConfig(map[string]any{
		"docs":       layout.EarlierRoot + "/docs/",
		"output":     layout.EarlierRoot + "/docs-cache/build/",
		"root_files": []any{layout.EarlierRoot + "/docs/_README.md", oldTemplate},
	}))
	testproject.WriteText(t, filepath.Join(dir, filepath.FromSlash(oldTemplate)), "# Agent notes\n")
	writeGeneratedRootClaude(t, dir, oldTemplate)
	testproject.Git(t, dir, "add", ".")
	testproject.Git(t, dir, "commit", "-q", "-m", "a generated root CLAUDE.md")

	dry := run(t, dir, "layout", "migrate", "--dry-run")
	for _, want := range []string{
		"move .stricttools/docs/ -> .strictmetadata/docs/",
		"move CLAUDE.md -> .claude/CLAUDE.md",
		"rewrite .claude/CLAUDE.md: header names " + claudeTemplate,
		"rewrite README.md: header names .strictmetadata/docs/_README.md",
	} {
		if !strings.Contains(dry.Stdout, want) {
			t.Errorf("the plan does not carry %q:\n%s", want, dry.Stdout)
		}
	}

	if result := run(t, dir, "layout", "migrate"); result.ExitCode != 0 {
		t.Fatalf("the move failed:\n%s\n%s", result.Stdout, result.Stderr)
	}
	moved := filepath.Join(dir, ".claude", "CLAUDE.md")
	if first, _, _ := strings.Cut(readText(t, moved), "\n"); first != readmeHeader(claudeTemplate) {
		t.Errorf(".claude/CLAUDE.md opens with %q", first)
	}
	if info, err := os.Stat(moved); err != nil || info.Mode().Perm() != 0o444 {
		t.Errorf(".claude/CLAUDE.md: %v, %v; want mode 0444", info, err)
	}
	if exists(filepath.Join(dir, "CLAUDE.md")) {
		t.Error("CLAUDE.md is still at the repository root")
	}
	if status := gitOutput(t, dir, "status", "--porcelain"); status != "" {
		t.Errorf("the move left uncommitted changes:\n%s", status)
	}
	if subject := strings.TrimSpace(gitOutput(t, dir, "log", "-1", "--format=%s")); subject !=
		"selfdoc layout migrate: move selfdoc's directories from .stricttools/ to .strictmetadata/ and move the generated CLAUDE.md to .claude/CLAUDE.md" {
		t.Errorf("the last commit is %q", subject)
	}
	if gen := run(t, dir, "gen", "--no-auto-commit"); gen.ExitCode != 0 {
		t.Errorf("gen after the move failed:\n%s\n%s", gen.Stdout, gen.Stderr)
	}
}

// A .claude/CLAUDE.md already beside the generated root file is refused: which
// one is current is not the move's to guess. Removing the one that is not
// clears the refusal.
func TestMigrateRefusesAnExistingDotClaudeClaudeAndItsFixClears(t *testing.T) {
	isolate(t)
	dir := rootClaudeProject(t)
	testproject.WriteText(t, filepath.Join(dir, ".claude", "CLAUDE.md"), "# Other notes\n")
	testproject.Git(t, dir, "add", ".claude/CLAUDE.md")
	testproject.Git(t, dir, "commit", "-q", "-m", "a second CLAUDE.md")

	result := run(t, dir, "layout", "migrate")
	if result.ExitCode == 0 {
		t.Fatal("the move went ahead over an existing .claude/CLAUDE.md")
	}
	fix := "git rm .claude/CLAUDE.md"
	if !strings.Contains(result.Stderr, fix) {
		t.Fatalf("the refusal does not name %q:\n%s", fix, result.Stderr)
	}
	testproject.Git(t, dir, "rm", "-q", ".claude/CLAUDE.md")
	testproject.Git(t, dir, "commit", "-q", "-m", "drop the second CLAUDE.md")
	if result := run(t, dir, "layout", "migrate"); result.ExitCode != 0 {
		t.Errorf("the move after the fix failed:\n%s", result.Stderr)
	}
}

// A move into a directory git ignores is refused, naming the ignore file, its
// line, and a narrower rule; narrowing the rule clears the refusal.
func TestMigrateRefusesAnIgnoredDotClaudeAndANarrowerRuleClears(t *testing.T) {
	isolate(t)
	dir := rootClaudeProject(t)
	testproject.WriteText(t, filepath.Join(dir, ".gitignore"), ".claude/\n")
	testproject.Git(t, dir, "add", ".gitignore")
	testproject.Git(t, dir, "commit", "-q", "-m", "ignore .claude/")

	result := run(t, dir, "layout", "migrate")
	if result.ExitCode == 0 {
		t.Fatal("the move went ahead into an ignored directory")
	}
	for _, want := range []string{"line 1 of .gitignore", "`.claude/settings.local.json`"} {
		if !strings.Contains(result.Stderr, want) {
			t.Errorf("the refusal does not name %q:\n%s", want, result.Stderr)
		}
	}
	if !exists(filepath.Join(dir, "CLAUDE.md")) {
		t.Fatal("the refusal moved CLAUDE.md")
	}

	testproject.WriteText(t, filepath.Join(dir, ".gitignore"), ".claude/settings.local.json\n")
	testproject.Git(t, dir, "commit", "-q", "-m", "narrow the rule", "--", ".gitignore")
	if result := run(t, dir, "layout", "migrate"); result.ExitCode != 0 {
		t.Fatalf("the move after the fix failed:\n%s", result.Stderr)
	}
	if tracked := strings.TrimSpace(gitOutput(t, dir, "ls-files", ".claude/CLAUDE.md")); tracked != ".claude/CLAUDE.md" {
		t.Errorf("git tracks %q", tracked)
	}
}
