package cli

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stricttools/selfdoc/internal/layout"
	"github.com/stricttools/selfdoc/internal/testproject"
	"github.com/stricttools/selfdoc/internal/vocabulary"
)

// `selfdoc layout migrate` moves a repository off the layout before this one:
// selfdoc's directories under the hidden .stricttools/ root, each under its
// bare function name.

// readmeHeader is the header of a README generated from the given template.
func readmeHeader(template string) string {
	return "<!-- Auto-generated by selfdoc from " + template + " — do not edit -->"
}

// previousLayoutProject is a committed repository on the previous layout:
// docs, generated state and cache under .stricttools/ with manifests naming
// selfdoc, another tool's directory beside them, selfdoc's block in the
// previous ignore file next to that tool's, a selfdoc.json naming the old
// paths, and a generated README whose header names the old template path.
func previousLayoutProject(t *testing.T, withOtherTool bool) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "project")
	previous := filepath.Join(dir, layout.PreviousRoot)
	testproject.WriteJSON(t, filepath.Join(dir, "selfdoc.json"), testproject.DefaultConfig(map[string]any{
		"docs":       layout.PreviousRoot + "/docs/",
		"output":     layout.PreviousRoot + "/docs-cache/build/",
		"root_files": []any{layout.PreviousRoot + "/docs/_README.md"},
	}))
	testproject.WriteText(t, filepath.Join(dir, "src", "__init__.py"), `"""Example package."""`+"\n")
	for _, name := range []string{layout.DocsName, layout.DocsStateName, layout.DocsCacheName} {
		testproject.WriteText(t, filepath.Join(previous, name, layout.ManifestFileName),
			layout.DirectoryManifestContent(layout.Owner))
	}
	testproject.WriteText(t, filepath.Join(previous, "docs", "index.md"), "# Test Project\n\nWelcome to the docs.\n")
	testproject.WriteText(t, filepath.Join(previous, "docs", "_README.md"), "# Test Project\n")
	testproject.WriteText(t, filepath.Join(previous, "docs-cache", "build", "index.html"), "<html></html>\n")
	ignore := "# BEGIN selfdoc -- derived from selfdoc's layout declaration\ndocs-cache/*\n!docs-cache/manifest.toml\n# END selfdoc\n"
	if withOtherTool {
		testproject.WriteText(t, filepath.Join(previous, "other-state", layout.ManifestFileName),
			layout.DirectoryManifestContent("othertool"))
		ignore += "\n# BEGIN othertool\nother-state/cache/\n# END othertool\n"
	}
	testproject.WriteText(t, filepath.Join(previous, layout.IgnoreFileName), ignore)
	testproject.WriteText(t, filepath.Join(dir, "README.md"),
		readmeHeader(layout.PreviousRoot+"/docs/_README.md")+"\n\n# Test Project\n")
	if err := os.Chmod(filepath.Join(dir, "README.md"), 0o444); err != nil {
		t.Fatal(err)
	}
	testproject.Git(t, dir, "init", "-q")
	testproject.Git(t, dir, "add", "selfdoc.json", "src", "README.md", layout.PreviousRoot)
	testproject.Git(t, dir, "commit", "-q", "-m", "previous layout")
	return dir
}

// Every command but the move refuses a repository still on the previous
// layout, naming the move; running the move clears the refusal.
func TestAnUnmigratedRepositoryIsRefusedNamingTheMove(t *testing.T) {
	isolate(t)
	dir := previousLayoutProject(t, false)
	for _, argv := range [][]string{
		{"check", "--no-auto-commit"},
		{"gen", "--no-auto-commit"},
		{"layout", "validate"},
		{"vocabulary", "accept", "frobnitz", "--meaning", "The widget.", "--no-auto-commit"},
	} {
		result := run(t, dir, argv...)
		if result.ExitCode == 0 || !strings.Contains(result.Stderr, "selfdoc layout migrate") {
			t.Errorf("%v exited %d without naming the move:\n%s", argv, result.ExitCode, result.Stderr)
		}
	}

	if result := run(t, dir, "layout", "migrate"); result.ExitCode != 0 {
		t.Fatalf("the move failed:\n%s\n%s", result.Stdout, result.Stderr)
	}
	result := run(t, dir, "layout", "validate")
	if result.ExitCode != 0 {
		t.Errorf("layout validate after the move exited %d:\n%s", result.ExitCode, result.Stderr)
	}
	if result := run(t, dir, "gen", "--no-auto-commit"); strings.Contains(result.Stderr, "selfdoc layout migrate") {
		t.Errorf("gen still refuses after the move:\n%s", result.Stderr)
	}
}

func TestMigrateDryRunPrintsThePlanAndChangesNothing(t *testing.T) {
	isolate(t)
	dir := previousLayoutProject(t, true)
	before := treeListing(t, dir)
	result := run(t, dir, "layout", "migrate", "--dry-run")
	if result.ExitCode != 0 {
		t.Fatalf("the dry run failed:\n%s\n%s", result.Stdout, result.Stderr)
	}
	for _, want := range []string{
		"move .stricttools/docs/ -> stricttools/docs/",
		"move .stricttools/docs-state/ -> stricttools/.docs-state/",
		"move .stricttools/docs-cache/ -> stricttools/.docs-cache/",
		"write stricttools/.gitignore",
		"write " + layout.TermsRel,
		`rewrite selfdoc.json: ".stricttools/docs/" -> "stricttools/docs/"`,
		"rewrite README.md: header names stricttools/docs/_README.md",
		"rewrite .stricttools/.gitignore",
	} {
		if !strings.Contains(result.Stdout, want) {
			t.Errorf("the plan does not carry %q:\n%s", want, result.Stdout)
		}
	}
	if after := treeListing(t, dir); after != before {
		t.Errorf("the dry run changed the tree:\nbefore:\n%s\nafter:\n%s", before, after)
	}
}

func TestMigrateMovesSelfdocsDirectoriesAndLeavesAnotherToolsAlone(t *testing.T) {
	isolate(t)
	dir := previousLayoutProject(t, true)
	result := run(t, dir, "--json", "layout", "migrate", "--no-auto-commit")
	if result.ExitCode != 0 {
		t.Fatalf("the move failed:\n%s\n%s", result.Stdout, result.Stderr)
	}
	for _, moved := range []string{"stricttools/docs/index.md", "stricttools/docs/_README.md",
		"stricttools/.docs-state/manifest.toml", "stricttools/.docs-cache/manifest.toml",
		"stricttools/.docs-cache/build/index.html", "stricttools/vocabulary/manifest.toml"} {
		if !exists(filepath.Join(dir, filepath.FromSlash(moved))) {
			t.Errorf("%s is missing after the move", moved)
		}
	}
	if got := readText(t, layout.Path(dir, layout.TermsRel)); got != vocabulary.EmptyTerms {
		t.Errorf("terms.toml = %q, want the empty vocabulary", got)
	}
	if _, err := vocabulary.Load(dir); err != nil {
		t.Errorf("the vocabulary the move wrote does not load: %v", err)
	}
	// Another tool's directory and its lines stay; selfdoc's block goes.
	if !exists(filepath.Join(dir, ".stricttools", "other-state", layout.ManifestFileName)) {
		t.Error("another tool's directory was moved or removed")
	}
	previousIgnore := readText(t, filepath.Join(dir, ".stricttools", layout.IgnoreFileName))
	if strings.Contains(previousIgnore, "BEGIN selfdoc") || !strings.Contains(previousIgnore, "other-state/cache/") {
		t.Errorf("the previous ignore file is\n%s", previousIgnore)
	}
	if ignore := readText(t, layout.IgnorePath(dir)); !strings.Contains(ignore, ".docs-cache/*") {
		t.Errorf("the derived ignore file is\n%s", ignore)
	}
	config := readJSON(t, filepath.Join(dir, "selfdoc.json"))
	if config["docs"] != "stricttools/docs/" || config["output"] != "stricttools/.docs-cache/build/" {
		t.Errorf("selfdoc.json docs/output = %v / %v", config["docs"], config["output"])
	}
	if files, _ := config["root_files"].([]any); len(files) != 1 || files[0] != "stricttools/docs/_README.md" {
		t.Errorf("selfdoc.json root_files = %v", config["root_files"])
	}
	readme := readText(t, filepath.Join(dir, "README.md"))
	if !strings.HasPrefix(readme, readmeHeader("stricttools/docs/_README.md")+"\n") {
		t.Errorf("README.md header is\n%s", readme)
	}
	if info, err := os.Stat(filepath.Join(dir, "README.md")); err != nil || info.Mode().Perm() != 0o444 {
		t.Errorf("README.md lost its read-only mode: %v", info.Mode())
	}
	payload := payloadOf(t, result)
	if moves, _ := payload["moves"].([]any); len(moves) != 3 {
		t.Errorf("payload moves = %v", payload["moves"])
	}
	if payload["removed_previous_root"] != false {
		t.Errorf("removed_previous_root = %v, want false while another tool's directory stays", payload["removed_previous_root"])
	}
}

func TestMigrateRemovesAnEmptiedPreviousRootAndCommits(t *testing.T) {
	isolate(t)
	dir := previousLayoutProject(t, false)
	result := run(t, dir, "layout", "migrate")
	if result.ExitCode != 0 {
		t.Fatalf("the move failed:\n%s\n%s", result.Stdout, result.Stderr)
	}
	if exists(filepath.Join(dir, ".stricttools")) {
		t.Error("the emptied previous root is still there")
	}
	status := gitOutput(t, dir, "status", "--porcelain")
	if strings.TrimSpace(status) != "" {
		t.Errorf("the move left uncommitted changes:\n%s", status)
	}
	if subject := gitOutput(t, dir, "log", "-1", "--format=%s"); !strings.Contains(subject, "selfdoc layout migrate") {
		t.Errorf("the last commit is %q", subject)
	}
}

func TestMigrateRefusesARepositoryWithNothingToMove(t *testing.T) {
	isolate(t)
	migrated := testproject.Make(t, nil)
	result := run(t, migrated, "layout", "migrate")
	if result.ExitCode == 0 || !strings.Contains(result.Stderr, "Nothing to migrate") ||
		!strings.Contains(result.Stderr, "already holds") {
		t.Errorf("an already migrated repository: exit %d\n%s", result.ExitCode, result.Stderr)
	}
	fresh := t.TempDir()
	result = run(t, fresh, "layout", "migrate")
	if result.ExitCode == 0 || !strings.Contains(result.Stderr, "selfdoc init") {
		t.Errorf("a repository never on the previous layout: exit %d\n%s", result.ExitCode, result.Stderr)
	}
}

// A move begun by hand and not finished is refused, with the commands that
// put it back; running them lets the move go through.
func TestMigrateRefusesAPartialMoveAndItsRemedyClears(t *testing.T) {
	isolate(t)
	dir := previousLayoutProject(t, false)
	testproject.MkdirAll(t, filepath.Join(dir, "stricttools"))
	testproject.Git(t, dir, "mv", ".stricttools/docs", "stricttools/docs")
	result := run(t, dir, "layout", "migrate")
	if result.ExitCode == 0 {
		t.Fatal("a partial move was accepted")
	}
	remedy := "git mv stricttools/docs .stricttools/docs"
	if !strings.Contains(result.Stderr, remedy) {
		t.Fatalf("the refusal does not name %q:\n%s", remedy, result.Stderr)
	}
	testproject.Git(t, dir, "mv", "stricttools/docs", ".stricttools/docs")
	if result := run(t, dir, "layout", "migrate", "--no-auto-commit"); result.ExitCode != 0 {
		t.Errorf("the move after the remedy failed:\n%s", result.Stderr)
	}
}

// treeListing lists every path under dir, outside .git, with its size, so a
// test can tell whether anything changed.
func treeListing(t *testing.T, dir string) string {
	t.Helper()
	var lines []string
	err := filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.Name() == ".git" {
			return filepath.SkipDir
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		content := ""
		if !entry.IsDir() {
			raw, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			content = string(raw)
		}
		rel, _ := filepath.Rel(dir, path)
		lines = append(lines, rel+" "+info.Mode().String()+" "+content)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return strings.Join(lines, "\n")
}

// gitOutput runs git in dir and returns what it printed.
func gitOutput(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	output, err := cmd.Output()
	if err != nil {
		t.Fatalf("git %v: %v", args, err)
	}
	return string(output)
}
