package check

import (
	"path/filepath"
	"strings"
	"testing"
)

// A CLAUDE.md at the repository root that an earlier selfdoc generated is an
// error naming the move; a hand-written one, and a generated .claude/CLAUDE.md,
// are not.
func TestAGeneratedRootClaudeIsReportedNamingTheMove(t *testing.T) {
	for _, testCase := range []struct {
		name    string
		path    string
		content string
		want    bool
	}{
		{
			name:    "generated at the repository root",
			path:    "CLAUDE.md",
			content: "<!-- Auto-generated by selfdoc from .strictmetadata/docs/_CLAUDE.md — do not edit -->\n\n# Notes\n",
			want:    true,
		},
		{
			name:    "hand-written at the repository root",
			path:    "CLAUDE.md",
			content: "# Notes\n",
			want:    false,
		},
		{
			name:    "generated under .claude/",
			path:    ".claude/CLAUDE.md",
			content: "<!-- Auto-generated by selfdoc from .strictmetadata/docs/_CLAUDE.md — do not edit -->\n\n# Notes\n",
			want:    false,
		},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			root := versionProject(t, pythonProjectConfig(), "")
			write(t, filepath.Join(root, filepath.FromSlash(testCase.path)), testCase.content)

			result, err := CheckDocs(root, nil, false, "", "", handle())
			if err != nil {
				t.Fatalf("CheckDocs: %v", err)
			}
			found := withCode(result.Lints, "generated-claude-md-at-repository-root")
			if got := len(found) > 0; got != testCase.want {
				t.Fatalf("generated-claude-md-at-repository-root fired = %v, want %v: %v",
					got, testCase.want, messagesOf(found))
			}
			if !testCase.want {
				return
			}
			if found[0].File() != "CLAUDE.md" {
				t.Errorf("file = %q, want CLAUDE.md", found[0].File())
			}
			if found[0].Severity() != "error" {
				t.Errorf("severity = %q, want error", found[0].Severity())
			}
			for _, want := range []string{".claude/CLAUDE.md", "selfdoc layout migrate --dry-run", "'selfdoc layout migrate'"} {
				if !strings.Contains(found[0].Message(), want) {
					t.Errorf("message does not name %q: %s", want, found[0].Message())
				}
			}
		})
	}
}
