// Package gitcommit commits the files a selfdoc command generated.
//
// Commands that write into the project directory -- `gen`, `check`, the
// post-build hash updates -- offer to commit what they wrote. The commit goes
// through rlsbl when it is installed (its Autogenerated trailer exempts the
// commit from changelog coverage), then safegit, then plain git, and is
// guarded against loops through the SELFDOC_AUTO_COMMIT environment variable:
// a git hook that runs selfdoc cannot start a commit of its own.
package gitcommit

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/stricttools/selfdoc/internal/effects"
	"github.com/stricttools/selfdoc/internal/util"
)

// guardVar is the environment variable that marks a selfdoc process as
// already running underneath an auto-commit. Its presence -- with any value --
// makes [AutoCommit] decline.
const guardVar = "SELFDOC_AUTO_COMMIT"

// probeTimeout bounds each read-only git probe (rev-parse, ls-files, diff,
// check-ignore).
const probeTimeout = 10 * time.Second

// commitTimeout bounds the commit itself, whichever tool performs it.
const commitTimeout = 30 * time.Second

// AutoCommit commits files in the git repository at cwd with message.
//
// committed reports whether a commit was made. unsettled reports that the
// commit was RECORDED rather than performed, which is what a handle in preview
// mode does with it; committed is then false, because nothing was committed.
// The returned error is never the repository's -- a missing git, a timed-out
// probe, a failing commit tool and a working tree with nothing to commit are
// all reported as committed false, with the tool's own stderr forwarded to
// this process's stderr. It is non-nil only when the effects handle itself
// fails, which a live run cannot do.
//
// Nothing is committed when:
//   - SELFDOC_AUTO_COMMIT is set, so a git hook running selfdoc cannot loop;
//   - cwd is not inside a git repository;
//   - every named file is unchanged, or untracked and gitignored.
//
// A tracked file is committed whether or not it matches a gitignore pattern
// (gitignore governs untracked files only), and a tracked file missing from
// disk is committed as a deletion.
func AutoCommit(files []string, message, cwd string, h *effects.Handle) (committed bool, unsettled bool, err error) {
	// Guard against re-entrant calls (e.g. a git hook triggers selfdoc).
	if os.Getenv(guardVar) != "" {
		return false, false, nil
	}

	// Check whether cwd is inside a git repo.
	result, err := h.Run(
		[]string{"git", "rev-parse", "--git-dir"},
		effects.Cwd(cwd),
		effects.CaptureOutput(),
		effects.Timeout(probeTimeout),
		effects.Read(),
	)
	if err != nil || result.ExitCode != 0 {
		return false, false, nil
	}

	committable, untrackedNew, err := classify(files, cwd, h)
	if err != nil {
		return false, false, err
	}

	// Filter gitignored files from the untracked candidates only.
	if len(untrackedNew) > 0 {
		ciResult, err := h.Run(
			[]string{"git", "check-ignore", "--stdin"},
			effects.Cwd(cwd),
			effects.CaptureOutput(),
			effects.Stdin([]byte(strings.Join(untrackedNew, "\n"))),
			effects.Timeout(probeTimeout),
			effects.Read(),
		)
		// An error -- a missing git, a timeout -- keeps every candidate, and
		// so does exit 1 (nothing is ignored) and exit 128 and up (git could
		// not answer).
		if err == nil && ciResult.ExitCode == 0 {
			ignored := make(map[string]bool)
			for _, line := range strings.Split(strings.TrimSpace(string(ciResult.Stdout)), "\n") {
				if line != "" {
					ignored[line] = true
				}
			}
			kept := untrackedNew[:0]
			for _, f := range untrackedNew {
				if !ignored[f] {
					kept = append(kept, f)
				}
			}
			untrackedNew = kept
		}
		committable = append(committable, untrackedNew...)
	}

	if len(committable) == 0 {
		return false, false, nil
	}

	// The child environment carries the loop guard.
	env := environWith(guardVar, "1")

	// Try rlsbl first, then safegit, fall back to plain git.
	//
	// No confirmation flag is passed. Both tools are strictcli apps, and
	// strictcli prompts only for commands that declare themselves
	// consequential; neither `rlsbl commit` nor `safegit commit` does, because
	// a commit is ordinary, undoable work. Passing --approve-consequential
	// here would be accepted (it is framework-global) but would state a
	// decision nobody asked for, so the bare argv is correct.
	var argv []string
	var label string
	switch {
	case have("rlsbl"):
		argv = append([]string{"rlsbl", "commit", "-m", message, "--"}, committable...)
		label = "rlsbl"
	case have("safegit"):
		argv = append([]string{"safegit", "commit", "-m", message, "--"}, committable...)
		label = "safegit"
	default:
		return plainGitCommit(committable, message, cwd, env, h)
	}

	result, err = h.Run(
		argv,
		effects.Cwd(cwd),
		effects.CaptureOutput(),
		effects.Env(env),
		effects.Timeout(commitTimeout),
		effects.Resource("commit:"+cwd),
	)
	if err != nil {
		if !childFailure(err) {
			return false, false, err
		}
		fmt.Fprintf(os.Stderr, "selfdoc: auto-commit failed (%s): %v\n", label, err)
		return false, false, nil
	}
	if result.Unsettled {
		// Recorded, not performed: nothing ran, so there is no exit status to
		// test. Reporting it unsettled is the honest answer.
		return false, true, nil
	}
	if result.ExitCode != 0 {
		os.Stderr.Write(result.Stderr)
		return false, false, nil
	}
	return true, false, nil
}

// classify splits files into the ones with something to commit and the
// untracked candidates still awaiting the gitignore filter.
//
// A file git cannot be asked about -- a probe that errored or timed out -- is
// skipped rather than guessed at.
func classify(files []string, cwd string, h *effects.Handle) (committable, untrackedNew []string, err error) {
	for _, f := range files {
		path := f
		if !filepath.IsAbs(f) {
			path = util.PathJoin(cwd, f)
		}

		lsResult, runErr := h.Run(
			[]string{"git", "ls-files", "--", f},
			effects.Cwd(cwd),
			effects.CaptureOutput(),
			effects.Timeout(probeTimeout),
			effects.Read(),
		)
		if runErr != nil {
			if !childFailure(runErr) {
				return nil, nil, runErr
			}
			continue
		}

		if lsResult.ExitCode == 0 && strings.TrimSpace(string(lsResult.Stdout)) != "" {
			// The file is tracked -- commit it regardless of gitignore.
			if !exists(path) {
				// Tracked but deleted from disk -- stage the deletion.
				committable = append(committable, f)
				continue
			}
			// Tracked and present -- commit it only if it has changes.
			diffResult, runErr := h.Run(
				[]string{"git", "diff", "--quiet", "--", f},
				effects.Cwd(cwd),
				effects.CaptureOutput(),
				effects.Timeout(probeTimeout),
				effects.Read(),
			)
			if runErr != nil {
				if !childFailure(runErr) {
					return nil, nil, runErr
				}
				continue
			}
			if diffResult.ExitCode != 0 {
				committable = append(committable, f)
			}
			continue
		}

		// The file is untracked -- collect it for the gitignore filter.
		if exists(path) {
			untrackedNew = append(untrackedNew, f)
		}
	}
	return committable, untrackedNew, nil
}

// plainGitCommit commits through plain git when neither rlsbl nor safegit is
// installed.
func plainGitCommit(committable []string, message, cwd string, env map[string]string, h *effects.Handle) (committed bool, unsettled bool, err error) {
	addResult, err := h.Run(
		append([]string{"git", "add", "--"}, committable...),
		effects.Cwd(cwd),
		effects.CaptureOutput(),
		effects.Env(env),
		effects.Timeout(commitTimeout),
	)
	if err != nil {
		if !childFailure(err) {
			return false, false, err
		}
		fmt.Fprintf(os.Stderr, "selfdoc: auto-commit failed (git): %v\n", err)
		return false, false, nil
	}

	commitArgv := append([]string{"git", "commit", "-m", message, "--"}, committable...)

	if addResult.Unsettled {
		// Recorded: the commit that would follow is recorded too, so the
		// preview stays complete without reading a status that does not exist.
		if _, err := h.Run(
			commitArgv,
			effects.Cwd(cwd),
			effects.CaptureOutput(),
			effects.Env(env),
			effects.Timeout(commitTimeout),
			effects.Resource("commit:"+cwd),
		); err != nil {
			return false, false, err
		}
		return false, true, nil
	}
	if addResult.ExitCode != 0 {
		os.Stderr.Write(addResult.Stderr)
		return false, false, nil
	}

	commitResult, err := h.Run(
		commitArgv,
		effects.Cwd(cwd),
		effects.CaptureOutput(),
		effects.Env(env),
		effects.Timeout(commitTimeout),
		effects.Resource("commit:"+cwd),
	)
	if err != nil {
		if !childFailure(err) {
			return false, false, err
		}
		fmt.Fprintf(os.Stderr, "selfdoc: auto-commit failed (git): %v\n", err)
		return false, false, nil
	}
	if commitResult.ExitCode != 0 {
		os.Stderr.Write(commitResult.Stderr)
		return false, false, nil
	}
	return true, false, nil
}

// have reports whether name is on PATH.
func have(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

// exists reports whether path is present on disk, following symlinks.
func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// environWith returns this process's environment as a map with key set to
// value, which is the complete environment the child receives.
func environWith(key, value string) map[string]string {
	env := make(map[string]string)
	for _, entry := range os.Environ() {
		if name, val, ok := strings.Cut(entry, "="); ok {
			env[name] = val
		}
	}
	env[key] = value
	return env
}

// childFailure reports whether err is the child process's own failure -- it
// timed out, or it could not be started at all -- rather than a failure of the
// effects handle.
//
// The distinction is the Python's (OSError, TimeoutExpired) except clause: a
// child that never ran is an ordinary outcome this package reports as "nothing
// committed", while a handle that could not record a mutation is a defect in
// the caller's own dispatch, and reporting that as "nothing committed" would
// hide it.
func childFailure(err error) bool {
	if errors.Is(err, effects.ErrTimeout) {
		return true
	}
	var execErr *exec.Error
	if errors.As(err, &execErr) {
		return true
	}
	var pathErr *os.PathError
	return errors.As(err, &pathErr)
}
