package sql

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stricttools/selfdoc/internal/extractors"
)

// writeTree writes a file tree under a fresh temporary directory and answers
// its root.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, content := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
	}
	return root
}

// newExtractor builds the extractor under test.
func newExtractor() extractors.Extractor { return New() }

// extract resolves one directive against a fixture root.
func extract(t *testing.T, root, directive string, attrs map[string]string, sourcePaths ...string) string {
	t.Helper()
	out, err := newExtractor().Extract(directive, attrs, nil, sourcePaths, root)
	if err != nil {
		t.Fatalf("extract %s: %v", directive, err)
	}
	return out
}

// schemaSource is the sample document the whole-output tests read: two tables
// with COMMENT ON documentation, two views, an enum and a composite type, and
// two functions, one of them documented.
const schemaSource = `-- Main schema for the application

CREATE TABLE users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email text NOT NULL UNIQUE,
    display_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id)
);

COMMENT ON TABLE users IS 'Registered user accounts';
COMMENT ON COLUMN users.id IS 'Unique user identifier';
COMMENT ON COLUMN users.email IS 'User email address, must be unique';
COMMENT ON COLUMN users.display_name IS 'Optional display name';

CREATE TABLE posts (
    id bigint GENERATED ALWAYS AS IDENTITY,
    author_id uuid NOT NULL REFERENCES users(id),
    title text NOT NULL,
    body text NOT NULL DEFAULT '',
    view_count integer NOT NULL DEFAULT 0,
    score numeric(10,2),
    tags text[],
    published_at timestamptz,
    CONSTRAINT posts_title_check CHECK (length(title) > 0)
);

COMMENT ON TABLE posts IS 'User-created blog posts';
COMMENT ON COLUMN posts.author_id IS 'Reference to the post author';
COMMENT ON COLUMN posts.tags IS 'Array of tag strings';

CREATE VIEW active_users AS
SELECT id, email, display_name
FROM users
WHERE is_active = true;

CREATE OR REPLACE VIEW recent_posts AS
SELECT p.id, p.title, u.display_name AS author
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.published_at > now() - interval '7 days';

CREATE TYPE status_type AS ENUM ('draft', 'published', 'archived');

CREATE TYPE address AS (
    street text,
    city text,
    zip_code text,
    country text
);

CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION soft_delete(target_id uuid)
RETURNS void AS $$
BEGIN
    UPDATE users SET is_active = false WHERE id = target_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_timestamp IS 'Auto-update timestamp trigger function';
`

// qualifiedSource carries schema-qualified tables and comments.
const qualifiedSource = `CREATE TABLE public.sessions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.users(id),
    token text NOT NULL,
    expires_at timestamptz NOT NULL
);

COMMENT ON TABLE public.sessions IS 'Active user sessions';
COMMENT ON COLUMN public.sessions.token IS 'Session authentication token';

CREATE TABLE IF NOT EXISTS audit.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_type text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
`

// generatedSource carries an identity column and a stored generated column.
const generatedSource = `CREATE TABLE products (
    id bigint GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL,
    price numeric(10,2) NOT NULL,
    tax_rate numeric(5,4) NOT NULL DEFAULT 0.0825,
    total_price numeric(10,2) GENERATED ALWAYS AS (price * (1 + tax_rate)) STORED,
    sku text NOT NULL UNIQUE
);
`

// dollarQuotedSource documents a table and a column with dollar-quoted
// strings, one of them carrying an apostrophe.
const dollarQuotedSource = `CREATE TABLE items (
    id serial PRIMARY KEY,
    name text NOT NULL
);

COMMENT ON TABLE items IS $$Items in the user's inventory$$;
COMMENT ON COLUMN items.name IS $desc$Item display name (can't be empty)$desc$;
`

// sqlProject is the four documents in one directory.
func sqlProject() map[string]string {
	return map[string]string{
		"sql/schema.sql":    schemaSource,
		"sql/qualified.sql": qualifiedSource,
		"sql/generated.sql": generatedSource,
		"sql/comments.sql":  dollarQuotedSource,
	}
}

func TestNameAndFileExtensions(t *testing.T) {
	t.Parallel()

	extractor := newExtractor()
	if got := extractor.Name(); got != "sql" {
		t.Errorf("Name() = %q, want sql", got)
	}
	exts := extractor.FileExtensions()
	if len(exts) != 1 || exts[0] != ".sql" {
		t.Errorf("FileExtensions() = %v, want [.sql]", exts)
	}
}

func TestRegisteredFactory(t *testing.T) {
	t.Parallel()

	extractor, ok, err := extractors.Lookup("sql")
	if err != nil || !ok {
		t.Fatalf("Lookup(sql) = %v, %v, %v", extractor, ok, err)
	}
	if extractor.Name() != "sql" {
		t.Errorf("registered extractor named %q", extractor.Name())
	}
}

func TestNeverDetected(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		files map[string]string
	}{
		{"empty directory", map[string]string{}},
		{"a directory full of DDL", sqlProject()},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, test.files)
			if newExtractor().Detect(root) {
				t.Error("Detect() = true; SQL is declared, never auto-detected")
			}
		})
	}
}

func TestPublicSymbols(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		source string
		want   []string
	}{
		{
			name:   "every kind of object, in document order",
			source: schemaSource,
			want: []string{
				"users", "posts", "active_users", "recent_posts",
				"status_type", "address", "update_timestamp", "soft_delete",
			},
		},
		{
			name:   "or replace",
			source: "CREATE OR REPLACE VIEW v AS SELECT 1;\n",
			want:   []string{"v"},
		},
		{
			name:   "if not exists",
			source: "CREATE TABLE IF NOT EXISTS events (id serial);\n",
			want:   []string{"events"},
		},
		{
			name:   "a schema-qualified name is listed unqualified",
			source: "CREATE TABLE public.users (id serial);\n",
			want:   []string{"users"},
		},
		{
			name: "a commented-out statement creates nothing",
			source: "-- CREATE TABLE commented (id serial);\n" +
				"/* CREATE TABLE blocked (id serial); */\n" +
				"CREATE TABLE real_table (id serial);\n",
			want: []string{"real_table"},
		},
		{
			name: "a replaced function is listed once",
			source: "CREATE FUNCTION f() RETURNS void AS $$ BEGIN END; $$;\n" +
				"CREATE OR REPLACE FUNCTION f() RETURNS void AS $$ BEGIN END; $$;\n",
			want: []string{"f"},
		},
		{
			name:   "lower-case keywords",
			source: "create table lower_case (id serial);\n",
			want:   []string{"lower_case"},
		},
		{
			name:   "empty document",
			source: "",
			want:   nil,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, map[string]string{"schema.sql": test.source})
			symbols, err := newExtractor().PublicSymbols(filepath.Join(root, "schema.sql"))
			if err != nil {
				t.Fatalf("PublicSymbols: %v", err)
			}
			if len(symbols) != len(test.want) {
				t.Fatalf("PublicSymbols = %v, want %v", symbols, test.want)
			}
			for i, name := range test.want {
				if symbols[i] != name {
					t.Errorf("symbol %d = %q, want %q", i, symbols[i], name)
				}
			}
		})
	}
}

func TestPublicSymbolsMissingFile(t *testing.T) {
	t.Parallel()

	symbols, err := newExtractor().PublicSymbols(filepath.Join(t.TempDir(), "nonexistent.sql"))
	if err != nil {
		t.Fatalf("PublicSymbols: %v", err)
	}
	if len(symbols) != 0 {
		t.Errorf("PublicSymbols = %v, want none", symbols)
	}
}

func TestParseCreateTableColumns(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name            string
		source          string
		wantTable       string
		wantSchema      string
		wantColumns     []column
		wantConstraints map[string][]string
	}{
		{
			name: "name, type, nullability and default",
			source: "CREATE TABLE users (\n" +
				"    id uuid NOT NULL,\n" +
				"    name text,\n" +
				"    age integer NOT NULL DEFAULT 0\n);\n",
			wantTable: "users",
			wantColumns: []column{
				{name: "id", colType: "uuid", nullable: false},
				{name: "name", colType: "text", nullable: true},
				{name: "age", colType: "integer", nullable: false, defaultValue: "0"},
			},
		},
		{
			name:      "the ordinary types",
			source:    "CREATE TABLE t (a integer, b text, c timestamptz, d uuid);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "a", colType: "integer", nullable: true},
				{name: "b", colType: "text", nullable: true},
				{name: "c", colType: "timestamptz", nullable: true},
				{name: "d", colType: "uuid", nullable: true},
			},
		},
		{
			name:      "array types",
			source:    "CREATE TABLE t (tags text[], ids integer[]);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "tags", colType: "text[]", nullable: true},
				{name: "ids", colType: "integer[]", nullable: true},
			},
		},
		{
			name:        "a user-defined type",
			source:      "CREATE TABLE t (status status_type NOT NULL);\n",
			wantTable:   "t",
			wantColumns: []column{{name: "status", colType: "status_type"}},
		},
		{
			name:      "parameterized types keep their parameters",
			source:    "CREATE TABLE t (score numeric(10,2), label varchar(255));\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "score", colType: "numeric(10,2)", nullable: true},
				{name: "label", colType: "varchar(255)", nullable: true},
			},
		},
		{
			name: "the default expressions",
			source: "CREATE TABLE t (\n" +
				"    a text NOT NULL DEFAULT 'hello',\n" +
				"    b integer DEFAULT 42,\n" +
				"    c boolean NOT NULL DEFAULT true,\n" +
				"    d timestamptz DEFAULT now()\n);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "a", colType: "text", defaultValue: "'hello'"},
				{name: "b", colType: "integer", nullable: true, defaultValue: "42"},
				{name: "c", colType: "boolean", defaultValue: "true"},
				{name: "d", colType: "timestamptz", nullable: true, defaultValue: "now()"},
			},
		},
		{
			name:      "an identity column",
			source:    "CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "id", colType: "bigint", nullable: true,
					defaultValue: "GENERATED ALWAYS AS IDENTITY"},
			},
		},
		{
			name:      "an identity column defaulted by the client",
			source:    "CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "id", colType: "bigint", nullable: true,
					defaultValue: "GENERATED BY DEFAULT AS IDENTITY"},
			},
		},
		{
			name: "a stored generated column",
			source: "CREATE TABLE t (\n" +
				"    price numeric(10,2) NOT NULL,\n" +
				"    tax numeric(10,2) NOT NULL,\n" +
				"    total numeric(10,2) GENERATED ALWAYS AS (price + tax) STORED\n);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "price", colType: "numeric(10,2)"},
				{name: "tax", colType: "numeric(10,2)"},
				{name: "total", colType: "numeric(10,2)", nullable: true,
					defaultValue: "GENERATED ALWAYS AS (price + tax) STORED"},
			},
		},
		{
			name:      "a quoted default keeps its type cast",
			source:    "CREATE TABLE t (data jsonb NOT NULL DEFAULT '{}'::jsonb);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "data", colType: "jsonb", defaultValue: "'{}'::jsonb"},
			},
		},
		{
			name:      "inline constraints",
			source:    "CREATE TABLE t (id serial PRIMARY KEY, email text UNIQUE, user_id uuid REFERENCES users(id));\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "id", colType: "serial", nullable: true},
				{name: "email", colType: "text", nullable: true},
				{name: "user_id", colType: "uuid", nullable: true},
			},
			wantConstraints: map[string][]string{
				"id":      {"PRIMARY KEY"},
				"email":   {"UNIQUE"},
				"user_id": {"REFERENCES users(id)"},
			},
		},
		{
			name: "table-level constraints declare no column",
			source: "CREATE TABLE t (\n    id serial,\n    name text,\n" +
				"    PRIMARY KEY (id),\n    UNIQUE (name),\n    CHECK (length(name) > 0)\n);\n",
			wantTable: "t",
			wantColumns: []column{
				{name: "id", colType: "serial", nullable: true},
				{name: "name", colType: "text", nullable: true},
			},
		},
		{
			name:        "a schema-qualified table",
			source:      "CREATE TABLE public.users (id serial);\n",
			wantTable:   "users",
			wantSchema:  "public",
			wantColumns: []column{{name: "id", colType: "serial", nullable: true}},
		},
		{
			name:        "if not exists",
			source:      "CREATE TABLE IF NOT EXISTS events (id serial);\n",
			wantTable:   "events",
			wantColumns: []column{{name: "id", colType: "serial", nullable: true}},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			tableList := parseCreateTable(test.source)
			if len(tableList) != 1 {
				t.Fatalf("parseCreateTable found %d tables, want 1", len(tableList))
			}
			got := tableList[0]
			if got.name != test.wantTable {
				t.Errorf("table name = %q, want %q", got.name, test.wantTable)
			}
			if got.schema != test.wantSchema {
				t.Errorf("table schema = %q, want %q", got.schema, test.wantSchema)
			}
			if len(got.columns) != len(test.wantColumns) {
				t.Fatalf("columns = %+v, want %d", got.columns, len(test.wantColumns))
			}
			for i, want := range test.wantColumns {
				col := got.columns[i]
				if col.name != want.name {
					t.Errorf("column %d name = %q, want %q", i, col.name, want.name)
				}
				if col.colType != want.colType {
					t.Errorf("column %q type = %q, want %q", col.name, col.colType, want.colType)
				}
				if col.nullable != want.nullable {
					t.Errorf("column %q nullable = %v, want %v", col.name, col.nullable, want.nullable)
				}
				if col.defaultValue != want.defaultValue {
					t.Errorf("column %q default = %q, want %q",
						col.name, col.defaultValue, want.defaultValue)
				}
				if wantConstraints, ok := test.wantConstraints[col.name]; ok {
					if len(col.constraints) != len(wantConstraints) {
						t.Fatalf("column %q constraints = %v, want %v",
							col.name, col.constraints, wantConstraints)
					}
					for j, wantConstraint := range wantConstraints {
						if col.constraints[j] != wantConstraint {
							t.Errorf("column %q constraint %d = %q, want %q",
								col.name, j, col.constraints[j], wantConstraint)
						}
					}
				}
			}
		})
	}
}

func TestParseCreateView(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		source     string
		wantName   string
		wantSchema string
	}{
		{name: "a view", source: "CREATE VIEW v AS SELECT 1;\n", wantName: "v"},
		{name: "or replace", source: "CREATE OR REPLACE VIEW v AS SELECT 1;\n", wantName: "v"},
		{
			name: "schema-qualified", source: "CREATE VIEW public.v AS SELECT 1;\n",
			wantName: "v", wantSchema: "public",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			views := parseCreateView(test.source)
			if len(views) != 1 {
				t.Fatalf("parseCreateView found %d views, want 1", len(views))
			}
			if views[0].name != test.wantName {
				t.Errorf("view name = %q, want %q", views[0].name, test.wantName)
			}
			if views[0].schema != test.wantSchema {
				t.Errorf("view schema = %q, want %q", views[0].schema, test.wantSchema)
			}
		})
	}
}

func TestParseCreateType(t *testing.T) {
	t.Parallel()

	t.Run("an enum", func(t *testing.T) {
		types := parseCreateType("CREATE TYPE status AS ENUM ('draft', 'published', 'archived');\n")
		if len(types) != 1 {
			t.Fatalf("parseCreateType found %d types, want 1", len(types))
		}
		got := types[0]
		if got.name != "status" || got.kind != "enum" {
			t.Errorf("type = %q of kind %q, want status of kind enum", got.name, got.kind)
		}
		want := []string{"draft", "published", "archived"}
		if len(got.values) != len(want) {
			t.Fatalf("values = %v, want %v", got.values, want)
		}
		for i, value := range want {
			if got.values[i] != value {
				t.Errorf("value %d = %q, want %q", i, got.values[i], value)
			}
		}
		if len(got.fields) != 0 {
			t.Errorf("an enum declared fields: %+v", got.fields)
		}
	})

	t.Run("an escaped quote in a label", func(t *testing.T) {
		types := parseCreateType("CREATE TYPE label AS ENUM ('it''s', 'they''re');\n")
		if len(types) != 1 {
			t.Fatalf("parseCreateType found %d types, want 1", len(types))
		}
		want := []string{"it's", "they're"}
		for i, value := range want {
			if types[0].values[i] != value {
				t.Errorf("value %d = %q, want %q", i, types[0].values[i], value)
			}
		}
	})

	t.Run("a composite", func(t *testing.T) {
		types := parseCreateType("CREATE TYPE address AS (\n    street text,\n" +
			"    city text,\n    zip_code text\n);\n")
		if len(types) != 1 {
			t.Fatalf("parseCreateType found %d types, want 1", len(types))
		}
		got := types[0]
		if got.name != "address" || got.kind != "composite" {
			t.Errorf("type = %q of kind %q, want address of kind composite", got.name, got.kind)
		}
		if len(got.values) != 0 {
			t.Errorf("a composite declared labels: %v", got.values)
		}
		want := []typeField{
			{name: "street", fieldType: "text"},
			{name: "city", fieldType: "text"},
			{name: "zip_code", fieldType: "text"},
		}
		if len(got.fields) != len(want) {
			t.Fatalf("fields = %+v, want %+v", got.fields, want)
		}
		for i, field := range want {
			if got.fields[i] != field {
				t.Errorf("field %d = %+v, want %+v", i, got.fields[i], field)
			}
		}
	})

	t.Run("schema-qualified", func(t *testing.T) {
		types := parseCreateType("CREATE TYPE public.status AS ENUM ('a', 'b');\n")
		if len(types) != 1 {
			t.Fatalf("parseCreateType found %d types, want 1", len(types))
		}
		if types[0].name != "status" || types[0].schema != "public" {
			t.Errorf("type = %q in schema %q, want status in public", types[0].name, types[0].schema)
		}
	})
}

func TestParseCreateFunction(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		source     string
		wantNames  []string
		wantSchema string
	}{
		{
			name: "a function",
			source: "CREATE FUNCTION do_thing(x integer) RETURNS void AS $$\n" +
				"BEGIN\nEND;\n$$ LANGUAGE plpgsql;\n",
			wantNames: []string{"do_thing"},
		},
		{
			name: "or replace",
			source: "CREATE OR REPLACE FUNCTION update_ts() RETURNS trigger AS $$\n" +
				"BEGIN END;\n$$ LANGUAGE plpgsql;\n",
			wantNames: []string{"update_ts"},
		},
		{
			name:       "schema-qualified",
			source:     "CREATE FUNCTION public.my_func() RETURNS void AS $$ BEGIN END; $$;\n",
			wantNames:  []string{"my_func"},
			wantSchema: "public",
		},
		{
			name: "a function replaced in the same document is one function",
			source: "CREATE OR REPLACE FUNCTION f() RETURNS void AS $$ BEGIN END; $$;\n" +
				"CREATE OR REPLACE FUNCTION f() RETURNS void AS $$ BEGIN END; $$;\n",
			wantNames: []string{"f"},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			functions := parseCreateFunction(test.source)
			if len(functions) != len(test.wantNames) {
				t.Fatalf("parseCreateFunction = %+v, want %v", functions, test.wantNames)
			}
			for i, name := range test.wantNames {
				if functions[i].name != name {
					t.Errorf("function %d = %q, want %q", i, functions[i].name, name)
				}
			}
			if functions[0].schema != test.wantSchema {
				t.Errorf("function schema = %q, want %q", functions[0].schema, test.wantSchema)
			}
		})
	}
}

func TestParseComments(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		source   string
		objType  string
		objName  string
		want     string
		contains []string
	}{
		{
			name:    "a table",
			source:  "COMMENT ON TABLE users IS 'Registered user accounts';\n",
			objType: "table", objName: "users", want: "Registered user accounts",
		},
		{
			name:    "a column",
			source:  "COMMENT ON COLUMN users.email IS 'User email address';\n",
			objType: "column", objName: "users.email", want: "User email address",
		},
		{
			name:    "an escaped quote",
			source:  "COMMENT ON TABLE items IS 'Items in the user''s inventory';\n",
			objType: "table", objName: "items", want: "Items in the user's inventory",
		},
		{
			name:    "a dollar quote with no tag",
			source:  "COMMENT ON TABLE items IS $$Dollar quoted text$$;\n",
			objType: "table", objName: "items", want: "Dollar quoted text",
		},
		{
			name:    "a dollar quote with a tag",
			source:  "COMMENT ON TABLE items IS $desc$Tagged dollar quote$desc$;\n",
			objType: "table", objName: "items", want: "Tagged dollar quote",
		},
		{
			name:    "a schema-qualified table",
			source:  "COMMENT ON TABLE public.sessions IS 'Active sessions';\n",
			objType: "table", objName: "public.sessions", want: "Active sessions",
		},
		{
			name:    "a schema-qualified column",
			source:  "COMMENT ON COLUMN public.sessions.token IS 'Auth token';\n",
			objType: "column", objName: "public.sessions.token", want: "Auth token",
		},
		{
			name:    "a view",
			source:  "COMMENT ON VIEW active_users IS 'Only active users';\n",
			objType: "view", objName: "active_users", want: "Only active users",
		},
		{
			name:    "a function",
			source:  "COMMENT ON FUNCTION update_ts IS 'Timestamp trigger';\n",
			objType: "function", objName: "update_ts", want: "Timestamp trigger",
		},
		{
			name:    "lower-case keywords",
			source:  "comment on table users is 'lower case keywords';\n",
			objType: "table", objName: "users", want: "lower case keywords",
		},
		{
			name: "a string spanning lines",
			source: "COMMENT ON TABLE users IS 'This is a\nmultiline comment\n" +
				"spanning three lines';\n",
			objType: "table", objName: "users",
			contains: []string{"multiline comment", "spanning three lines"},
		},
		{
			name: "a comment set to NULL leaves the previous one standing",
			source: "COMMENT ON TABLE users IS 'Some text';\n" +
				"COMMENT ON TABLE users IS NULL;\n",
			objType: "table", objName: "users", want: "Some text",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			comments := parseComments(test.source)
			got := comments.get(test.objType, test.objName)
			if len(test.contains) > 0 {
				for _, want := range test.contains {
					if !strings.Contains(got, want) {
						t.Errorf("comment = %q, missing %q", got, want)
					}
				}
				return
			}
			if got != test.want {
				t.Errorf("comment = %q, want %q", got, test.want)
			}
		})
	}
}

func TestRefGroupsByKind(t *testing.T) {
	t.Parallel()

	root := writeTree(t, sqlProject())
	got := extract(t, root, "ref", map[string]string{"path": "sql/schema.sql"})

	want := "## `schema.sql`\n\n" +
		"### Tables\n\n" +
		"- `users` -- Registered user accounts\n" +
		"- `posts` -- User-created blog posts\n\n" +
		"### Views\n\n" +
		"- `active_users`\n" +
		"- `recent_posts`\n\n" +
		"### Types\n\n" +
		"- `status_type` -- ENUM: `draft`, `published`, `archived`\n" +
		"- `address` -- COMPOSITE: `street text`, `city text`, `zip_code text`, `country text`\n\n" +
		"### Functions\n\n" +
		"- `update_timestamp` -- Auto-update timestamp trigger function\n" +
		"- `soft_delete`"

	if got != want {
		t.Errorf("ref output\n got: %q\nwant: %q", got, want)
	}
}

func TestRefWithTarget(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		target string
		want   string
	}{
		{
			name: "a documented table", target: "users",
			want: "### `users`\n\nRegistered user accounts",
		},
		{
			name: "an undocumented view", target: "active_users",
			want: "### `active_users`",
		},
		{
			name: "an enum renders its labels", target: "status_type",
			want: "### `status_type`\n\nENUM: `draft`, `published`, `archived`",
		},
		{
			name: "a composite renders its fields", target: "address",
			want: "### `address`\n\nCOMPOSITE: `street text`, `city text`, " +
				"`zip_code text`, `country text`",
		},
		{
			name: "an undocumented function", target: "soft_delete",
			want: "### `soft_delete`",
		},
		{
			name: "a documented function", target: "update_timestamp",
			want: "### `update_timestamp`\n\nAuto-update timestamp trigger function",
		},
		{
			name: "a name the document does not create", target: "missing",
			want: "> *[selfdoc: symbol 'missing' not found in 'sql/schema.sql']*",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, sqlProject())
			got := extract(t, root, "ref", map[string]string{
				"path": "sql/schema.sql", "target": test.target,
			})
			if got != test.want {
				t.Errorf("ref target\n got: %q\nwant: %q", got, test.want)
			}
		})
	}
}

func TestRefErrors(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		files map[string]string
		attrs map[string]string
		want  string
	}{
		{
			name:  "no path",
			attrs: map[string]string{"path": ""},
			want:  "> *[selfdoc: :::ref requires a file path argument]*",
		},
		{
			name:  "missing file",
			attrs: map[string]string{"path": "sql/missing.sql"},
			want:  "> *[selfdoc: 'sql/missing.sql' not found]*",
		},
		{
			name:  "a document that creates nothing",
			files: map[string]string{"empty.sql": "-- just a comment\nSELECT 1;\n"},
			attrs: map[string]string{"path": "empty.sql"},
			want:  "> *[selfdoc: no CREATE objects found in 'empty.sql']*",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, test.files)
			if got := extract(t, root, "ref", test.attrs); got != test.want {
				t.Errorf("ref = %q, want %q", got, test.want)
			}
		})
	}
}

func TestProseDesc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		path  string
		attrs map[string]string
		want  string
	}{
		{
			name:  "a documented table",
			attrs: map[string]string{"path": "sql/schema.sql", "target": "users"},
			want:  "Registered user accounts",
		},
		{
			name:  "a bare target matches a schema-qualified statement",
			attrs: map[string]string{"path": "sql/qualified.sql", "target": "sessions"},
			want:  "Active user sessions",
		},
		{
			name:  "a dollar-quoted comment",
			attrs: map[string]string{"path": "sql/comments.sql", "target": "items"},
			want:  "Items in the user's inventory",
		},
		{
			name:  "no path",
			attrs: map[string]string{"path": "", "target": "users"},
			want:  "> *[selfdoc: :::prose-desc requires a file path argument]*",
		},
		{
			name:  "no target",
			attrs: map[string]string{"path": "sql/schema.sql"},
			want:  "> *[selfdoc: prose-desc requires a target table name for SQL files]*",
		},
		{
			name:  "an undocumented table",
			attrs: map[string]string{"path": "sql/schema.sql", "target": "missing"},
			want:  "> *[selfdoc: no comment found for table 'missing']*",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, sqlProject())
			if got := extract(t, root, "prose-desc", test.attrs); got != test.want {
				t.Errorf("prose-desc = %q, want %q", got, test.want)
			}
		})
	}
}

func TestTableSchema(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		attrs map[string]string
		want  string
	}{
		{
			name:  "a table with column comments",
			attrs: map[string]string{"path": "sql/schema.sql", "target": "users"},
			want: "| Column | Type | Nullable | Default | Description |\n" +
				"| --- | --- | --- | --- | --- |\n" +
				"| `id` | `uuid` | NOT NULL | gen_random_uuid() | Unique user identifier |\n" +
				"| `email` | `text` | NOT NULL |  | User email address, must be unique |\n" +
				"| `display_name` | `text` |  |  | Optional display name |\n" +
				"| `created_at` | `timestamptz` | NOT NULL | now() |  |\n" +
				"| `updated_at` | `timestamptz` | NOT NULL | now() |  |\n" +
				"| `is_active` | `boolean` | NOT NULL | true |  |",
		},
		{
			name:  "identity, references, arrays and parameterized types",
			attrs: map[string]string{"path": "sql/schema.sql", "target": "posts"},
			want: "| Column | Type | Nullable | Default | Description |\n" +
				"| --- | --- | --- | --- | --- |\n" +
				"| `id` | `bigint` |  | GENERATED ALWAYS AS IDENTITY |  |\n" +
				"| `author_id` | `uuid` | NOT NULL |  | Reference to the post author |\n" +
				"| `title` | `text` | NOT NULL |  |  |\n" +
				"| `body` | `text` | NOT NULL | '' |  |\n" +
				"| `view_count` | `integer` | NOT NULL | 0 |  |\n" +
				"| `score` | `numeric(10,2)` |  |  |  |\n" +
				"| `tags` | `text[]` |  |  | Array of tag strings |\n" +
				"| `published_at` | `timestamptz` |  |  |  |",
		},
		{
			name:  "one table needs no target",
			attrs: map[string]string{"path": "sql/generated.sql"},
			want: "| Column | Type | Nullable | Default | Description |\n" +
				"| --- | --- | --- | --- | --- |\n" +
				"| `id` | `bigint` |  | GENERATED ALWAYS AS IDENTITY |  |\n" +
				"| `name` | `text` | NOT NULL |  |  |\n" +
				"| `price` | `numeric(10,2)` | NOT NULL |  |  |\n" +
				"| `tax_rate` | `numeric(5,4)` | NOT NULL | 0.0825 |  |\n" +
				"| `total_price` | `numeric(10,2)` |  | " +
				"GENERATED ALWAYS AS (price * (1 + tax_rate)) STORED |  |\n" +
				"| `sku` | `text` | NOT NULL |  |  |",
		},
		{
			name:  "several tables each get a heading",
			attrs: map[string]string{"path": "sql/qualified.sql"},
			want: "### `sessions`\n\n" +
				"| Column | Type | Nullable | Default | Description |\n" +
				"| --- | --- | --- | --- | --- |\n" +
				"| `id` | `uuid` | NOT NULL | gen_random_uuid() |  |\n" +
				"| `user_id` | `uuid` | NOT NULL |  |  |\n" +
				"| `token` | `text` | NOT NULL |  | Session authentication token |\n" +
				"| `expires_at` | `timestamptz` | NOT NULL |  |  |\n" +
				"### `events`\n\n" +
				"| Column | Type | Nullable | Default | Description |\n" +
				"| --- | --- | --- | --- | --- |\n" +
				"| `id` | `bigint` |  | GENERATED BY DEFAULT AS IDENTITY |  |\n" +
				"| `event_type` | `text` | NOT NULL |  |  |\n" +
				"| `payload` | `jsonb` | NOT NULL | '{}'::jsonb |  |\n" +
				"| `created_at` | `timestamptz` | NOT NULL | now() |  |",
		},
		{
			name:  "dollar-quoted column comments",
			attrs: map[string]string{"path": "sql/comments.sql"},
			want: "| Column | Type | Nullable | Default | Description |\n" +
				"| --- | --- | --- | --- | --- |\n" +
				"| `id` | `serial` |  |  |  |\n" +
				"| `name` | `text` | NOT NULL |  | Item display name (can't be empty) |",
		},
		{
			name:  "a table the document does not create",
			attrs: map[string]string{"path": "sql/schema.sql", "target": "missing"},
			want:  "> *[selfdoc: table 'missing' not found in 'sql/schema.sql']*",
		},
		{
			name:  "no path",
			attrs: map[string]string{"path": ""},
			want:  "> *[selfdoc: :::table-schema requires a file path argument]*",
		},
		{
			name:  "missing file",
			attrs: map[string]string{"path": "sql/missing.sql"},
			want:  "> *[selfdoc: 'sql/missing.sql' not found]*",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, sqlProject())
			if got := extract(t, root, "table-schema", test.attrs); got != test.want {
				t.Errorf("table-schema\n got: %q\nwant: %q", got, test.want)
			}
		})
	}
}

func TestTableSchemaNoTables(t *testing.T) {
	t.Parallel()

	root := writeTree(t, map[string]string{
		"views.sql": "CREATE VIEW v AS SELECT 1;\n",
	})
	got := extract(t, root, "table-schema", map[string]string{"path": "views.sql"})
	want := "> *[selfdoc: no tables found in 'views.sql']*"
	if got != want {
		t.Errorf("table-schema = %q, want %q", got, want)
	}
}

func TestTableSchemaConfigDelegation(t *testing.T) {
	t.Parallel()

	root := writeTree(t, map[string]string{"conf.json": `{"a": 1, "b": "two"}`})
	got := extract(t, root, "table-schema", map[string]string{"path": "conf.json"})
	want := "| Key | Type | Value |\n| --- | --- | --- |\n" +
		"| `a` | integer | `1` |\n| `b` | string | `\"two\"` |"
	if got != want {
		t.Errorf("table-schema = %q, want %q", got, want)
	}
}

func TestUnknownDirective(t *testing.T) {
	t.Parallel()

	got := extract(t, t.TempDir(), "code-help", map[string]string{"path": "schema.sql"})
	want := "> *[selfdoc: unknown directive 'code-help' for sql extractor]*"
	if got != want {
		t.Errorf("unknown directive = %q, want %q", got, want)
	}
}

func TestResolvePath(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		pathArg     string
		sourcePaths []string
		wantSuffix  string
		wantEmpty   bool
	}{
		{name: "a sql file", pathArg: "sql/schema.sql", wantSuffix: "schema.sql"},
		{name: "a directory of sql files", pathArg: "sql", wantSuffix: "sql"},
		{
			name: "through a source path", pathArg: "schema.sql",
			sourcePaths: []string{"sql/"}, wantSuffix: "schema.sql",
		},
		{name: "implicit extension", pathArg: "sql/schema", wantSuffix: "schema.sql"},
		{name: "not found", pathArg: "nonexistent.sql", wantEmpty: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, sqlProject())
			got := newExtractor().ResolvePath(test.pathArg, test.sourcePaths, root)
			if test.wantEmpty {
				if got != "" {
					t.Fatalf("ResolvePath = %q, want the empty string", got)
				}
				return
			}
			if !strings.HasSuffix(got, test.wantSuffix) {
				t.Errorf("ResolvePath = %q, want a path ending in %q", got, test.wantSuffix)
			}
		})
	}
}

func TestSymbolDetails(t *testing.T) {
	t.Parallel()

	type wantParam struct {
		name      string
		paramType string
	}

	tests := []struct {
		name             string
		symbol           string
		wantNil          bool
		params           []wantParam
		returnType       string
		returnDocumented bool
	}{
		{
			name:       "a function with a parameter",
			symbol:     "soft_delete",
			params:     []wantParam{{"target_id", "uuid"}},
			returnType: "void",
		},
		{
			name:             "a documented function with no parameters",
			symbol:           "update_timestamp",
			returnType:       "trigger",
			returnDocumented: true,
		},
		{name: "a table is not a function", symbol: "users", wantNil: true},
		{name: "a view is not a function", symbol: "active_users", wantNil: true},
		{name: "a type is not a function", symbol: "status_type", wantNil: true},
		{name: "a name the document does not create", symbol: "missing", wantNil: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := writeTree(t, sqlProject())
			got, err := newExtractor().SymbolDetails(
				filepath.Join(root, "sql", "schema.sql"), test.symbol)
			if err != nil {
				t.Fatalf("SymbolDetails: %v", err)
			}
			if test.wantNil {
				if got != nil {
					t.Fatalf("SymbolDetails = %+v, want nothing", got)
				}
				return
			}
			if got == nil {
				t.Fatal("SymbolDetails = nothing, want details")
			}
			if len(got.Params) != len(test.params) {
				t.Fatalf("params = %+v, want %d", got.Params, len(test.params))
			}
			for i, want := range test.params {
				param := got.Params[i]
				if param.Name != want.name {
					t.Errorf("param %d name = %q, want %q", i, param.Name, want.name)
				}
				if want.paramType == "" {
					if param.Type != nil {
						t.Errorf("param %d type = %q, want none", i, *param.Type)
					}
				} else if param.Type == nil || *param.Type != want.paramType {
					t.Errorf("param %d type = %v, want %q", i, param.Type, want.paramType)
				}
				if param.Documented {
					t.Errorf("param %d reported documented; SQL documents no parameters", i)
				}
			}
			if test.returnType == "" {
				if got.ReturnType != nil {
					t.Errorf("return type = %q, want none", *got.ReturnType)
				}
			} else if got.ReturnType == nil || *got.ReturnType != test.returnType {
				t.Errorf("return type = %v, want %q", got.ReturnType, test.returnType)
			}
			if got.ReturnDocumented != test.returnDocumented {
				t.Errorf("return documented = %v, want %v", got.ReturnDocumented, test.returnDocumented)
			}
		})
	}
}

func TestStripComments(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		source string
		want   string
	}{
		{
			name:   "a line comment",
			source: "SELECT 1; -- trailing\nSELECT 2;\n",
			want:   "SELECT 1; \nSELECT 2;\n",
		},
		{
			name:   "a block comment",
			source: "SELECT /* inline */ 1;\n",
			want:   "SELECT  1;\n",
		},
		{
			name:   "a marker inside a single-quoted string is not a comment",
			source: "SELECT '-- not a comment';\n",
			want:   "SELECT '-- not a comment';\n",
		},
		{
			name:   "a marker inside a dollar-quoted string is not a comment",
			source: "SELECT $$-- not a comment$$;\n",
			want:   "SELECT $$-- not a comment$$;\n",
		},
		{
			name:   "an escaped quote keeps the string open",
			source: "SELECT 'it''s -- fine';\n",
			want:   "SELECT 'it''s -- fine';\n",
		},
		{
			name:   "an unterminated block comment ends the document",
			source: "SELECT 1;\n/* forever\n",
			want:   "SELECT 1;\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := stripComments(test.source); got != test.want {
				t.Errorf("stripComments = %q, want %q", got, test.want)
			}
		})
	}
}
