// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.4.0
// schema:              selfdoc-lint-registry (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package lints

import "github.com/stricttools/strictspec/go/strictspec"

// GENERATED_BY is the strictspec release that produced this file. It is
// INFORMATIONAL: pairing is on GENERATED_CODE_FORMAT below, so a later release
// of the runtime reads this file unchanged, and no tool may derive a dependency
// floor from this string.
const GENERATED_BY = "0.4.0"

// GENERATED_CODE_FORMAT is the shape of generated code this file was written
// to. The runtime pairing guard hard-errors unless this format is one the
// linked runtime reads; the remedy is regeneration.
const GENERATED_CODE_FORMAT = 2

// SCHEMA_FORMAT_VERSION is the document format_version this validator accepts.
const SCHEMA_FORMAT_VERSION = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"lint-registry.schema.toml": `# strictspec schema -- selfdoc lint-code registry.
#
# Governs internal/lints/lints.toml: the declarative document that is the single
# source of truth for every lint code selfdoc can emit, with its severity and
# its one-line description. The generated validator
# (selfdoc_lint_registry_gen.go) validates the document at load time in package
# lints; a malformed registry is a hard error at startup, before any check
# runs.
#
# SCOPE (honest subset): this schema owns the raw DOCUMENT SHAPE of the registry
# -- the code grammar, the severity enum, per-entry required fields,
# unknown-key rejection, and unique codes. It does NOT model where a code is
# emitted from, which condition raises it, or whether the JSON output schema
# and the documentation table agree with it. Those are selfdoc-native and both
# enforced structurally: LintResult derives severity from this registry and
# refuses an unregistered code, the JSON output schema's code enum is pinned to
# the registry by a test, and the documentation table is rendered from the
# registry by the "table-lints" directive rather than written out beside it.

name = "selfdoc-lint-registry"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "LintRegistry"
description = "The selfdoc lint-code registry: one entry per emittable lint code (code, severity, description)."

[types.LintRegistry]
type = "record"

[types.LintRegistry.fields.format_version]
type = "integer"
required = true
description = "Document format-version gate. v1 documents carry 1."

[types.LintRegistry.fields.lints]
type = "array"
required = true
min_len = 1
description = "The registered lint codes, in documentation order."
[types.LintRegistry.fields.lints.item]
type = "LintDescriptor"

# Codes are unique across the registry (the loader keys a dict by them).
[[types.LintRegistry.constraints]]
form = "unique-by"
collection = "lints"
field = "code"
normalization = "none"

# --- named types ---

[types.LintDescriptor]
type = "record"
description = "Registry entry for a single lint code."

[types.LintDescriptor.fields.code]
type = "string"
required = true
non_empty = true
regex = '^[A-Z][A-Z0-9]*[0-9]{3}$'
description = "Lint code. Grammar: an uppercase family name followed by a three-digit number (SEO001, DRIFT001, POST005)."

[types.LintDescriptor.fields.severity]
type = "enum"
required = true
values = ["error", "warning"]
description = "\"error\" fails the check run; \"warning\" is informational and never changes the exit code."

[types.LintDescriptor.fields.description]
type = "string"
required = true
non_empty = true
description = "One-line description of what the rule checks, rendered verbatim into the documentation's lint-rule table."
`,
}

const embeddedMainFile = "lint-registry.schema.toml"

var program *strictspec.Program

func init() {
	// Pairing: this file's generated-code format must be one the runtime reads.
	strictspec.RequireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*LintRegistry, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindLintRegistry(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*LintRegistry, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindLintRegistry(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*LintRegistry, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindLintRegistry(v), nil
}

// LintRegistry is the frozen typed binding of the "LintRegistry" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type LintRegistry struct {
	FormatVersion int64
	Lints         []*LintDescriptor
}

func bindLintRegistry(v strictspec.Value) *LintRegistry {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &LintRegistry{}
	if fv, ok := v.Field("format_version"); ok {
		out.FormatVersion = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("lints"); ok {
		out.Lints = bindSlice(fv, func(e strictspec.Value) *LintDescriptor { return bindLintDescriptor(e) })
	}
	return out
}

// WithFormatVersion returns a copy of LintRegistry with FormatVersion set to the given value.
func (x *LintRegistry) WithFormatVersion(v int64) *LintRegistry {
	c := *x
	c.FormatVersion = v
	return &c
}

// WithLints returns a copy of LintRegistry with Lints set to the given value.
func (x *LintRegistry) WithLints(v []*LintDescriptor) *LintRegistry {
	c := *x
	c.Lints = v
	return &c
}

// LintDescriptor is the frozen typed binding of the "LintDescriptor" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type LintDescriptor struct {
	Code        string
	Severity    string
	Description string
}

func bindLintDescriptor(v strictspec.Value) *LintDescriptor {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &LintDescriptor{}
	if fv, ok := v.Field("code"); ok {
		out.Code = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("severity"); ok {
		out.Severity = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithCode returns a copy of LintDescriptor with Code set to the given value.
func (x *LintDescriptor) WithCode(v string) *LintDescriptor {
	c := *x
	c.Code = v
	return &c
}

// WithSeverity returns a copy of LintDescriptor with Severity set to the given value.
func (x *LintDescriptor) WithSeverity(v string) *LintDescriptor {
	c := *x
	c.Severity = v
	return &c
}

// WithDescription returns a copy of LintDescriptor with Description set to the given value.
func (x *LintDescriptor) WithDescription(v string) *LintDescriptor {
	c := *x
	c.Description = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
