// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.4.0
// schema:              selfdoc-directive-catalogue (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package catalog

import "github.com/stricttools/strictspec/go/strictspec"

// GENERATED_BY is the strictspec release that produced this file. It is
// INFORMATIONAL: pairing is on GENERATED_CODE_FORMAT below, so a later release
// of the runtime reads this file unchanged, and no tool may derive a dependency
// floor from this string.
const GENERATED_BY = "0.4.0"

// GENERATED_CODE_FORMAT is the shape of generated code this file was written
// to. The runtime pairing guard hard-errors unless this format is one the
// linked runtime reads; the remedy is regeneration.
const GENERATED_CODE_FORMAT = 2

// SCHEMA_FORMAT_VERSION is the document format_version this validator accepts.
const SCHEMA_FORMAT_VERSION = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"directive-descriptor.schema.toml": `# strictspec schema -- selfdoc built-in directive catalogue.
#
# Governs internal/catalog/directives.toml: the declarative descriptor document
# that is the single source of truth for the shipped ("core") built-in
# directives. The generated validator (selfdoc_directive_catalogue_gen.go)
# validates the document at load time in package catalog; a malformed catalogue
# is a hard error at startup, before any directive is dispatched.
#
# SCOPE (honest subset): this schema owns the raw DOCUMENT SHAPE of the catalogue
# -- the name grammar, the code/content category enum, required/optional attr
# lists, per-descriptor required fields, unknown-key rejection, and unique names.
# It does NOT model the RUNTIME couplings selfdoc keeps native: which resolver
# runs for which name (the content-resolution dispatch + extractor path),
# custom and future directive names (which carry no descriptor and skip attr
# enforcement by design), and the catalog-vs-resolver attribute-consistency oracle (a curated
# test). Those remain selfdoc-native by declaration.

name = "selfdoc-directive-catalogue"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "DirectiveCatalogue"
description = "The selfdoc built-in directive catalogue: one descriptor per shipped directive (name, description, category, required/optional attributes, example)."

[types.DirectiveCatalogue]
type = "record"

[types.DirectiveCatalogue.fields.format_version]
type = "integer"
required = true
description = "Document format-version gate. v1 documents carry 1."

[types.DirectiveCatalogue.fields.directives]
type = "array"
required = true
min_len = 1
description = "The shipped built-in directives, in catalogue order."
[types.DirectiveCatalogue.fields.directives.item]
type = "DirectiveDescriptor"

# Directive names are unique across the catalogue (the loader keys a dict by them).
[[types.DirectiveCatalogue.constraints]]
form = "unique-by"
collection = "directives"
field = "name"
normalization = "none"

# --- named types ---

[types.DirectiveDescriptor]
type = "record"
description = "Metadata for a single built-in directive."

[types.DirectiveDescriptor.fields.name]
type = "string"
required = true
non_empty = true
regex = '^[a-zA-Z][\w-]*$'
description = "Directive name. Grammar: starts with a letter, then word chars or hyphens (the directive-name PATTERN)."

[types.DirectiveDescriptor.fields.description]
type = "string"
required = true
non_empty = true
description = "One-line human description shown in the directive reference table."

[types.DirectiveDescriptor.fields.category]
type = "enum"
required = true
values = ["code", "content"]
description = "\"code\" directives dispatch to a language extractor (path-based); \"content\" directives resolve language-agnostically."

[types.DirectiveDescriptor.fields.required_attrs]
type = "array"
required = true
description = "Attribute names the directive requires (may be empty)."
[types.DirectiveDescriptor.fields.required_attrs.item]
type = "string"

[types.DirectiveDescriptor.fields.optional_attrs]
type = "array"
required = true
description = "Attribute names the directive optionally accepts (may be empty)."
[types.DirectiveDescriptor.fields.optional_attrs.item]
type = "string"

[types.DirectiveDescriptor.fields.example]
type = "string"
required = true
non_empty = true
description = "A representative usage example."
`,
}

const embeddedMainFile = "directive-descriptor.schema.toml"

var program *strictspec.Program

func init() {
	// Pairing: this file's generated-code format must be one the runtime reads.
	strictspec.RequireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*DirectiveCatalogue, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindDirectiveCatalogue(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*DirectiveCatalogue, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindDirectiveCatalogue(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*DirectiveCatalogue, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindDirectiveCatalogue(v), nil
}

// DirectiveCatalogue is the frozen typed binding of the "DirectiveCatalogue" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type DirectiveCatalogue struct {
	FormatVersion int64
	Directives    []*DirectiveDescriptor
}

func bindDirectiveCatalogue(v strictspec.Value) *DirectiveCatalogue {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &DirectiveCatalogue{}
	if fv, ok := v.Field("format_version"); ok {
		out.FormatVersion = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("directives"); ok {
		out.Directives = bindSlice(fv, func(e strictspec.Value) *DirectiveDescriptor { return bindDirectiveDescriptor(e) })
	}
	return out
}

// WithFormatVersion returns a copy of DirectiveCatalogue with FormatVersion set to the given value.
func (x *DirectiveCatalogue) WithFormatVersion(v int64) *DirectiveCatalogue {
	c := *x
	c.FormatVersion = v
	return &c
}

// WithDirectives returns a copy of DirectiveCatalogue with Directives set to the given value.
func (x *DirectiveCatalogue) WithDirectives(v []*DirectiveDescriptor) *DirectiveCatalogue {
	c := *x
	c.Directives = v
	return &c
}

// DirectiveDescriptor is the frozen typed binding of the "DirectiveDescriptor" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type DirectiveDescriptor struct {
	Name          string
	Description   string
	Category      string
	RequiredAttrs []string
	OptionalAttrs []string
	Example       string
}

func bindDirectiveDescriptor(v strictspec.Value) *DirectiveDescriptor {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &DirectiveDescriptor{}
	if fv, ok := v.Field("name"); ok {
		out.Name = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("category"); ok {
		out.Category = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("required_attrs"); ok {
		out.RequiredAttrs = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("optional_attrs"); ok {
		out.OptionalAttrs = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("example"); ok {
		out.Example = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithName returns a copy of DirectiveDescriptor with Name set to the given value.
func (x *DirectiveDescriptor) WithName(v string) *DirectiveDescriptor {
	c := *x
	c.Name = v
	return &c
}

// WithDescription returns a copy of DirectiveDescriptor with Description set to the given value.
func (x *DirectiveDescriptor) WithDescription(v string) *DirectiveDescriptor {
	c := *x
	c.Description = v
	return &c
}

// WithCategory returns a copy of DirectiveDescriptor with Category set to the given value.
func (x *DirectiveDescriptor) WithCategory(v string) *DirectiveDescriptor {
	c := *x
	c.Category = v
	return &c
}

// WithRequiredAttrs returns a copy of DirectiveDescriptor with RequiredAttrs set to the given value.
func (x *DirectiveDescriptor) WithRequiredAttrs(v []string) *DirectiveDescriptor {
	c := *x
	c.RequiredAttrs = v
	return &c
}

// WithOptionalAttrs returns a copy of DirectiveDescriptor with OptionalAttrs set to the given value.
func (x *DirectiveDescriptor) WithOptionalAttrs(v []string) *DirectiveDescriptor {
	c := *x
	c.OptionalAttrs = v
	return &c
}

// WithExample returns a copy of DirectiveDescriptor with Example set to the given value.
func (x *DirectiveDescriptor) WithExample(v string) *DirectiveDescriptor {
	c := *x
	c.Example = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
