// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.4.0
// schema:              selfdoc-vocabulary-terms (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package termsschema

import "github.com/stricttools/strictspec/go/strictspec"

// GENERATED_BY is the strictspec release that produced this file. It is
// INFORMATIONAL: pairing is on GENERATED_CODE_FORMAT below, so a later release
// of the runtime reads this file unchanged, and no tool may derive a dependency
// floor from this string.
const GENERATED_BY = "0.4.0"

// GENERATED_CODE_FORMAT is the shape of generated code this file was written
// to. The runtime pairing guard hard-errors unless this format is one the
// linked runtime reads; the remedy is regeneration.
const GENERATED_CODE_FORMAT = 2

// SCHEMA_FORMAT_VERSION is the document format_version this validator accepts.
const SCHEMA_FORMAT_VERSION = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"vocabulary-terms.schema.toml": `# strictspec schema -- a project's vocabulary: the words its pages may use that
# the English word list does not carry, and the terms its pages may not use.
#
# Governs stricttools/vocabulary/terms.toml, and the baseline of the same shape
# embedded in the selfdoc binary (internal/vocabulary/baseline.toml). The
# generated validator (internal/vocabulary/termsschema/selfdoc_vocabulary_terms_gen.go) is
# what vocabulary.Load validates each file against, so a list that reaches the
# spell check has already been through here.
#
# THE KEY REGISTRY. A record is closed: a key not declared here is refused
# rather than silently ignored. Both arrays are optional, so a file carrying
# only the format-version gate is a valid, empty vocabulary.
#
# SCOPE (honest subset): this schema owns each file's DOCUMENT SHAPE -- the key
# registry, the required fields, the kind enum and the lexeme class of a word.
# It does not own the order of the entries, duplicates, a word both accepted
# and rejected (within one file or across the baseline and the project), or
# whether any page uses an accepted word; those are selfdoc-native, because
# they span entries, files or pages: a load-time refusal for the conflict, and
# the VOCAB lints for the rest.

name = "selfdoc-vocabulary-terms"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "Terms"
description = "A project's vocabulary: the accepted words, each with its meaning, and the rejected terms, each with the reason."

[types.Terms]
type = "record"
description = "One vocabulary file."

[types.Terms.fields.format_version]
type = "integer"
required = true
description = "Document format-version gate. v1 files carry 1."

[types.Terms.fields.accepted]
type = "array"
required = false
description = "The accepted words, kept sorted by word."
[types.Terms.fields.accepted.item]
type = "AcceptedTerm"

[types.Terms.fields.rejected]
type = "array"
required = false
description = "The rejected terms, kept sorted by pattern."
[types.Terms.fields.rejected.item]
type = "RejectedTerm"

# --- named types ---

[types.Term]
type = "string"
non_empty = true
regex = '^\S(?:.*\S)?$'
description = "A word, a phrase or a pattern: non-empty, with no whitespace at either end."

[types.AcceptedTerm]
type = "record"
description = "One word the project's pages may use."

[types.AcceptedTerm.fields.word]
type = "Term"
required = true
description = "The word, as the project spells it. Matched case-insensitively."

[types.AcceptedTerm.fields.meaning]
type = "string"
required = true
non_empty = true
description = "What the word means in this project, in one sentence."

[types.AcceptedTerm.fields.aliases]
type = "array"
required = false
description = "Other spellings of the same word, accepted with it."
[types.AcceptedTerm.fields.aliases.item]
type = "Term"

[types.RejectedTerm]
type = "record"
description = "One term the project's pages may not use."

[types.RejectedTerm.fields.pattern]
type = "Term"
required = true
description = "The rejected text. Matched case-insensitively on word boundaries."

[types.RejectedTerm.fields.kind]
type = "enum"
required = true
values = ["word", "phrase", "suffix", "prefix"]
description = "How the pattern matches: a whole word, a whole phrase, the end of a word, or the start of a word."

[types.RejectedTerm.fields.reason]
type = "string"
required = true
non_empty = true
description = "Why the term is rejected, shown beside every place a page uses it."
`,
}

const embeddedMainFile = "vocabulary-terms.schema.toml"

var program *strictspec.Program

func init() {
	// Pairing: this file's generated-code format must be one the runtime reads.
	strictspec.RequireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*Terms, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindTerms(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*Terms, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindTerms(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*Terms, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindTerms(v), nil
}

// Terms is the frozen typed binding of the "Terms" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Terms struct {
	FormatVersion int64
	Accepted      []*AcceptedTerm
	Rejected      []*RejectedTerm
}

func bindTerms(v strictspec.Value) *Terms {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Terms{}
	if fv, ok := v.Field("format_version"); ok {
		out.FormatVersion = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("accepted"); ok {
		out.Accepted = bindSlice(fv, func(e strictspec.Value) *AcceptedTerm { return bindAcceptedTerm(e) })
	}
	if fv, ok := v.Field("rejected"); ok {
		out.Rejected = bindSlice(fv, func(e strictspec.Value) *RejectedTerm { return bindRejectedTerm(e) })
	}
	return out
}

// WithFormatVersion returns a copy of Terms with FormatVersion set to the given value.
func (x *Terms) WithFormatVersion(v int64) *Terms {
	c := *x
	c.FormatVersion = v
	return &c
}

// WithAccepted returns a copy of Terms with Accepted set to the given value.
func (x *Terms) WithAccepted(v []*AcceptedTerm) *Terms {
	c := *x
	c.Accepted = v
	return &c
}

// WithRejected returns a copy of Terms with Rejected set to the given value.
func (x *Terms) WithRejected(v []*RejectedTerm) *Terms {
	c := *x
	c.Rejected = v
	return &c
}

// AcceptedTerm is the frozen typed binding of the "AcceptedTerm" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type AcceptedTerm struct {
	Word    string
	Meaning string
	Aliases []string
}

func bindAcceptedTerm(v strictspec.Value) *AcceptedTerm {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &AcceptedTerm{}
	if fv, ok := v.Field("word"); ok {
		out.Word = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("meaning"); ok {
		out.Meaning = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("aliases"); ok {
		out.Aliases = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	return out
}

// WithWord returns a copy of AcceptedTerm with Word set to the given value.
func (x *AcceptedTerm) WithWord(v string) *AcceptedTerm {
	c := *x
	c.Word = v
	return &c
}

// WithMeaning returns a copy of AcceptedTerm with Meaning set to the given value.
func (x *AcceptedTerm) WithMeaning(v string) *AcceptedTerm {
	c := *x
	c.Meaning = v
	return &c
}

// WithAliases returns a copy of AcceptedTerm with Aliases set to the given value.
func (x *AcceptedTerm) WithAliases(v []string) *AcceptedTerm {
	c := *x
	c.Aliases = v
	return &c
}

// RejectedTerm is the frozen typed binding of the "RejectedTerm" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type RejectedTerm struct {
	Pattern string
	Kind    string
	Reason  string
}

func bindRejectedTerm(v strictspec.Value) *RejectedTerm {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &RejectedTerm{}
	if fv, ok := v.Field("pattern"); ok {
		out.Pattern = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("kind"); ok {
		out.Kind = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("reason"); ok {
		out.Reason = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithPattern returns a copy of RejectedTerm with Pattern set to the given value.
func (x *RejectedTerm) WithPattern(v string) *RejectedTerm {
	c := *x
	c.Pattern = v
	return &c
}

// WithKind returns a copy of RejectedTerm with Kind set to the given value.
func (x *RejectedTerm) WithKind(v string) *RejectedTerm {
	c := *x
	c.Kind = v
	return &c
}

// WithReason returns a copy of RejectedTerm with Reason set to the given value.
func (x *RejectedTerm) WithReason(v string) *RejectedTerm {
	c := *x
	c.Reason = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
