#!/usr/bin/env python3
"""Move one repository onto selfdoc's .stricttools/ layout.

selfdoc keeps every directory it owns under one hidden directory at the
repository root: the handwritten pages at .stricttools/docs/, the generated
pages and the rest of the generated-and-committed state at
.stricttools/docs-state/, the build output and the version cache at
.stricttools/docs-cache/, the posts at .stricttools/posts/, and the vocabulary
at .stricttools/vocabulary/. There is no migrator inside selfdoc and no dual
reading: a repository is moved once, by hand, with this script, and every
selfdoc command refuses it until it is.

The script never creates .stricttools/ itself: the directory is the
repository's own grant of permission, so it refuses when it is absent. What it
DOES write is the ownership manifest of each function directory it needs --
one line, 'owner = "selfdoc"' -- because a manifest is the permission to write
into the directory it sits in, and the move is what brings that directory into
being. A directory that already exists with a manifest naming another tool is
refused instead.

What it does, in order:

  1. Reads selfdoc.json for the paths the repository declares today.
  2. Captures the site's current URL set from the sitemap the last build wrote,
     keeping a copy under .stricttools/docs-cache/, so the same set can be
     demanded of the build that follows the move.
  3. Writes the ownership manifests and moves every tracked file as ONE commit,
     through 'safegit commit --moved': a page carrying selfdoc's generated-page
     marker goes to the generated pages directory, every other page goes to the
     handwritten one, and the rest of the old tool-state directory goes to its
     function directory.
  4. Rewrites the paths the moved content names -- the config keys, the root
     ignore file, and the old paths spelled inside pages, posts and templates
     -- as a SECOND commit through 'safegit commit'.
  5. Builds the site again with the selfdoc binary resolved in step 0 and
     refuses to finish unless the URL set is identical to the one captured in
     step 2. The commits stay in place; the difference is printed.

The binary that build runs is resolved BEFORE step 3, so a machine with no
selfdoc is refused while the repository is still untouched: --selfdoc when it
is named, otherwise 'selfdoc' on PATH, otherwise bin/selfdoc in the project.

Usage:

    python3 scripts/move-to-stricttools-layout.py --dry-run
    python3 scripts/move-to-stricttools-layout.py --apply
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT_DIR = ".stricttools"
MANIFEST_FILE = "manifest.toml"
OWNER_KEY = "owner"
OWNER = "selfdoc"
MANIFEST_CONTENT = f'{OWNER_KEY} = "{OWNER}"\n'
DEPRECATED_ROOT = ".selfdoc"
GENERATED_MARKER_PREFIX = "<!-- generated by selfdoc gen"

DOCS_REL = f"{ROOT_DIR}/docs"
DOCS_STATE_REL = f"{ROOT_DIR}/docs-state"
DOCS_CACHE_REL = f"{ROOT_DIR}/docs-cache"
POSTS_REL = f"{ROOT_DIR}/posts"
VOCABULARY_REL = f"{ROOT_DIR}/vocabulary"
GENERATED_PAGES_REL = f"{DOCS_STATE_REL}/pages"
OUTPUT_REL = f"{DOCS_CACHE_REL}/build"
VERSIONS_REL = f"{DOCS_CACHE_REL}/versions"

# The function directories, in the order a report lists them. Which of them one
# move needs is derived from the move itself: the cache always, because the
# capture below and the build that follows the move both write into it, plus
# whichever directories the planned moves carry content into.
FUNCTION_ORDER = ["docs", "docs-state", "docs-cache", "posts", "vocabulary"]
CACHE_FUNCTION = "docs-cache"

# The file the pre-move URL set is kept in, inside the uncommitted cache.
SITEMAP_CAPTURE = f"{DOCS_CACHE_REL}/sitemap-before-move.xml"

# The state files the old tool-state directory held, and where each one lives
# now.
STATE_FILES = {
    "manifest.json": f"{DOCS_STATE_REL}/manifest.json",
    "post-manifest.json": f"{DOCS_STATE_REL}/post-manifest.json",
    "revisions.json": f"{DOCS_STATE_REL}/revisions.json",
}
STATE_DIRS = {
    "hashes": f"{DOCS_STATE_REL}/hashes",
    "data": f"{DOCS_STATE_REL}/data",
}


class Refusal(Exception):
    """A condition the person running the script has to clear first."""


def run(argv: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(argv, cwd=cwd, capture_output=True, text=True)


def load_config(project: Path) -> dict:
    path = project / "selfdoc.json"
    if not path.is_file():
        raise Refusal(f"{path} does not exist, so this is not a selfdoc project.")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except ValueError as error:
        raise Refusal(f"{path} is not valid JSON: {error}") from error


def declared_paths(config: dict) -> tuple[str, str, str]:
    """The docs, output and posts paths the repository declares today."""
    docs = config.get("docs") or "docs/"
    output = config.get("output") or "docs/_build/"
    posts = ".selfdoc/posts/"
    block = config.get("posts")
    if isinstance(block, dict) and isinstance(block.get("dir"), str):
        posts = block["dir"]
    return docs.rstrip("/"), output.rstrip("/"), posts.rstrip("/")


def require_tool_root(project: Path) -> None:
    """Refuse a repository that has not made the hidden directory itself."""
    root = project / ROOT_DIR
    if not root.is_dir():
        raise Refusal(
            f"{ROOT_DIR}/ does not exist. This script never creates it: the directory is "
            f"the repository's own grant. Create {ROOT_DIR}/ and run this again. The "
            f"script writes the {MANIFEST_FILE} of each directory it needs inside it -- "
            f"{manifest_rel('docs')} and its siblings -- each one holding:"
            f"\n{MANIFEST_CONTENT.rstrip()}"
        )


def manifest_rel(name: str) -> str:
    """One function directory's ownership manifest, repository-relative."""
    return f"{ROOT_DIR}/{name}/{MANIFEST_FILE}"


def declared_owner(path: Path) -> str | None:
    """The owner a manifest on disk names, or None when it names none."""
    for line in path.read_text(encoding="utf-8").splitlines():
        key, separator, value = line.partition("=")
        if separator and key.strip() == OWNER_KEY:
            return value.strip().strip('"').strip("'")
    return None


def needed_functions(moves: list[tuple[str, str]]) -> list[str]:
    """The function directories this move writes into, in declaration order."""
    needed = {CACHE_FUNCTION}
    for _, new in moves:
        parts = new.split("/")
        if len(parts) > 2 and parts[0] == ROOT_DIR:
            needed.add(parts[1])
    return [name for name in FUNCTION_ORDER if name in needed]


def plan_manifests(project: Path, moves: list[tuple[str, str]]) -> list[str]:
    """The ownership manifests this move has to write, repository-relative.

    A directory already carrying a manifest that names selfdoc needs none. One
    naming another tool is not selfdoc's to move into, and is refused.
    """
    planned = []
    for name in needed_functions(moves):
        relative = manifest_rel(name)
        path = project / relative
        if not path.is_file():
            planned.append(relative)
            continue
        owner = declared_owner(path)
        if owner != OWNER:
            raise Refusal(
                f"{ROOT_DIR}/{name} declares {owner!r} as its owner, not {OWNER!r}, so "
                f"selfdoc may not move content into it. Resolve the ownership of "
                f"{ROOT_DIR}/{name} with that tool, then run this again."
            )
    return planned


def tracked_files(project: Path, prefix: str) -> list[str]:
    """Every tracked path under prefix, as repository-relative slash paths."""
    result = run(["git", "ls-files", "-z", "--", prefix], project)
    if result.returncode != 0:
        raise Refusal(f"git ls-files {prefix} failed: {result.stderr.strip()}")
    return [name for name in result.stdout.split("\0") if name]


def untracked_entries(project: Path, prefix: str) -> list[str]:
    """Every file under prefix that git does not track, ignored ones included."""
    if not (project / prefix).exists():
        return []
    found = []
    for path in sorted((project / prefix).rglob("*")):
        if path.is_dir():
            continue
        relative = path.relative_to(project).as_posix()
        result = run(["git", "ls-files", "--error-unmatch", "--", relative], project)
        if result.returncode != 0:
            found.append(relative)
    return found


def is_generated_page(path: Path) -> bool:
    try:
        return GENERATED_MARKER_PREFIX in path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False


def plan_moves(project: Path, docs_rel: str, output_rel: str, posts_rel: str) -> list[tuple[str, str]]:
    """Every move the layout needs, as (old, new) repository-relative pairs."""
    moves: list[tuple[str, str]] = []

    for name in tracked_files(project, docs_rel):
        if name == docs_rel or name.startswith(output_rel + "/"):
            continue
        relative = name[len(docs_rel) + 1:]
        if name.endswith(".md") and is_generated_page(project / name):
            moves.append((name, f"{GENERATED_PAGES_REL}/{relative}"))
        else:
            moves.append((name, f"{DOCS_REL}/{relative}"))

    for name in tracked_files(project, posts_rel):
        relative = name[len(posts_rel) + 1:]
        moves.append((name, f"{POSTS_REL}/{relative}"))

    for name in tracked_files(project, DEPRECATED_ROOT):
        if posts_rel and (name == posts_rel or name.startswith(posts_rel + "/")):
            continue
        relative = name[len(DEPRECATED_ROOT) + 1:]
        head = relative.split("/", 1)[0]
        if relative in STATE_FILES:
            moves.append((name, STATE_FILES[relative]))
        elif head in STATE_DIRS:
            moves.append((name, f"{STATE_DIRS[head]}/{relative[len(head) + 1:]}"))
        elif head == "cache":
            moves.append((name, f"{VERSIONS_REL}/{relative[len('cache') + 1:]}"))
        else:
            moves.append((name, f"{DOCS_STATE_REL}/{relative}"))

    return moves


def capture_sitemap(project: Path, output_rel: str, apply: bool) -> set[str]:
    """The URL set the site publishes today, kept for the comparison after."""
    capture = project / SITEMAP_CAPTURE
    built = project / output_rel / "sitemap.xml"
    if built.is_file():
        if apply:
            capture.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(built, capture)
        return sitemap_urls(built)
    if capture.is_file():
        return sitemap_urls(capture)
    raise Refusal(
        f"{output_rel}/sitemap.xml does not exist, so the URL set this move must preserve "
        f"is unknown. Build the site once with a selfdoc release that predates the layout "
        f"flip -- 'go run github.com/smm-h/selfdoc@v0.41.0 build' -- and run this again."
    )


def sitemap_urls(path: Path) -> set[str]:
    tree = ElementTree.parse(path)
    return {
        (element.text or "").strip()
        for element in tree.iter()
        if element.tag.endswith("loc") and (element.text or "").strip()
    }


def rewrite_map(docs_rel: str, output_rel: str, posts_rel: str) -> list[tuple[str, str]]:
    """The literal path rewrites the moved content needs, longest first."""
    pairs = [
        # The config keys by their exact JSON spelling, slashed or not, so a
        # repository that declares `"docs": "docs"` is rewritten too.
        (f'"docs": "{docs_rel}/"', f'"docs": "{DOCS_REL}/"'),
        (f'"docs": "{docs_rel}"', f'"docs": "{DOCS_REL}/"'),
        (f'"output": "{output_rel}/"', f'"output": "{OUTPUT_REL}/"'),
        (f'"output": "{output_rel}"', f'"output": "{OUTPUT_REL}/"'),
        (f'"dir": "{posts_rel}/"', f'"dir": "{POSTS_REL}/"'),
        (f'"dir": "{posts_rel}"', f'"dir": "{POSTS_REL}/"'),
        (f"{DEPRECATED_ROOT}/post-manifest.json", f"{DOCS_STATE_REL}/post-manifest.json"),
        (f"{DEPRECATED_ROOT}/manifest.json", f"{DOCS_STATE_REL}/manifest.json"),
        (f"{DEPRECATED_ROOT}/revisions.json", f"{DOCS_STATE_REL}/revisions.json"),
        (f"{DEPRECATED_ROOT}/hashes/", f"{DOCS_STATE_REL}/hashes/"),
        (f"{DEPRECATED_ROOT}/data/", f"{DOCS_STATE_REL}/data/"),
        (f"{DEPRECATED_ROOT}/cache/", f"{VERSIONS_REL}/"),
        (f"{posts_rel}/", f"{POSTS_REL}/"),
        (f"{output_rel}/", f"{OUTPUT_REL}/"),
        (f"{docs_rel}/", f"{DOCS_REL}/"),
    ]
    # A repository already spelling a path the new way needs no rewrite for it.
    return [(old, new) for old, new in pairs if old != new]


REWRITABLE_SUFFIXES = {".md", ".toml", ".json", ".txt"}


def rewritable_files(project: Path, moves: list[tuple[str, str]]) -> list[tuple[Path, str]]:
    """The files whose text may name a moved path, each as (file to read, the
    name it will have once the moves are done).

    A dry run reads the moved content where it still sits, and reports the
    rewrite under the name the move gives it, so the preview covers every file
    the apply run will touch rather than only the ones that never move.
    """
    found = []
    for name in ("selfdoc.json", ".gitignore", "README.md", "CLAUDE.md"):
        path = project / name
        if path.is_file():
            found.append((path, name))
    moved = {new for _, new in moves}
    for old, new in moves:
        if Path(new).suffix not in REWRITABLE_SUFFIXES:
            continue
        source = project / old
        if not source.is_file():
            source = project / new
        if source.is_file():
            found.append((source, new))
    # A file that already sits at its final place and was not moved.
    for prefix in (DOCS_REL, GENERATED_PAGES_REL, POSTS_REL):
        root = project / prefix
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            relative = path.relative_to(project).as_posix()
            if path.is_file() and path.suffix in REWRITABLE_SUFFIXES and relative not in moved:
                found.append((path, relative))
    return found


def plan_rewrites(
    project: Path, pairs: list[tuple[str, str]], moves: list[tuple[str, str]], output_rel: str
) -> list[tuple[str, str, str]]:
    """Every (name, before, after) rewrite, one entry per changed file."""
    planned = []
    for path, name in rewritable_files(project, moves):
        try:
            before = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        after = before
        if name == ".gitignore":
            # The root ignore file's line for the old build output goes
            # rather than being rewritten: the derived ignore file inside the
            # tool-state directory covers the new one.
            after = drop_stale_ignore_lines(after, output_rel)
        for old, new in pairs:
            after = replace_path(after, old, new)
        if after != before:
            planned.append((name, before, after))
    return planned


def replace_path(text: str, old: str, new: str) -> str:
    """Every mention of the repository path `old` in `text`, rewritten to `new`.

    A mention is the path at the start of a path: not preceded by a word
    character, a slash or a hyphen. That leaves alone the same letters inside
    a longer name (`mydocs/`) and inside an address on another host
    (`https://example.org/docs/`), neither of which this repository moved.
    """
    return re.sub(r"(?<![\w/-])" + re.escape(old), lambda _: new, text)


def changed_lines(before: str, after: str) -> list[str]:
    """The rewrite as a unified diff, body lines only.

    A line-by-line pairing would misreport every line after a dropped one, so
    the report is a real diff.
    """
    diff = difflib.unified_diff(
        before.split("\n"), after.split("\n"), lineterm="", n=0)
    return [line for line in diff if not line.startswith(("---", "+++"))]


def drop_stale_ignore_lines(text: str, output_rel: str) -> str:
    """The root ignore file's line for the old build output is not needed: the
    derived ignore file inside the tool-state directory covers the new one."""
    kept = []
    for line in text.split("\n"):
        if line.strip().rstrip("/") == output_rel:
            continue
        kept.append(line)
    return "\n".join(kept)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true",
                      help="print every move and every rewrite, and change nothing")
    mode.add_argument("--apply", action="store_true",
                      help="perform the moves and the rewrites, as two commits")
    parser.add_argument("--project", default=".",
                        help="the repository to move; defaults to the working directory")
    parser.add_argument("--selfdoc", default=None,
                        help="the selfdoc binary the after-the-move build runs, relative to "
                             "the project or absolute; with none named, 'selfdoc' on PATH is "
                             "used, then bin/selfdoc inside the project")
    parser.add_argument("--expect-manifests", type=int, default=None,
                        help="fail unless the plan writes exactly this many ownership manifests")
    parser.add_argument("--expect-moves", type=int, default=None,
                        help="fail unless the plan holds exactly this many moves")
    parser.add_argument("--expect-rewrites", type=int, default=None,
                        help="fail unless the plan rewrites exactly this many files")
    args = parser.parse_args()

    project = Path(args.project).resolve()
    try:
        return move(project, args)
    except Refusal as refusal:
        print(f"refused: {refusal}", file=sys.stderr)
        return 1


def find_selfdoc(project: Path, declared: str | None) -> tuple[str | None, str | None]:
    """resolve_selfdoc's answer, or the refusal it would raise, without raising.

    The plan names the binary when there is one; only --apply turns its
    absence into the refusal, and does so before the first write.
    """
    try:
        return resolve_selfdoc(project, declared), None
    except Refusal as refusal:
        return None, str(refusal)


def resolve_selfdoc(project: Path, declared: str | None) -> str:
    """The selfdoc binary the after-the-move build runs, as an absolute path.

    Demanded by --apply before anything is written. The build is the move's
    last step, so a binary found missing there leaves both commits in place and
    nothing verified -- and calling a path that does not exist raises rather
    than refusing. A binary named with --selfdoc must be there; with none named
    the PATH answer is taken, and then bin/selfdoc inside the project. A dry
    run reports the answer, or the refusal, and never raises it.
    """
    if declared is not None:
        candidate = Path(declared) if os.path.isabs(declared) else project / declared
        if not (candidate.is_file() and os.access(candidate, os.X_OK)):
            raise Refusal(
                f"--selfdoc names {candidate}, which is not an executable file."
            )
        return str(candidate.resolve())
    found = shutil.which("selfdoc")
    if found:
        return str(Path(found).resolve())
    fallback = project / "bin" / "selfdoc"
    if fallback.is_file() and os.access(fallback, os.X_OK):
        return str(fallback.resolve())
    raise Refusal(
        "the build that verifies this move needs a selfdoc binary, and there is "
        "none: 'selfdoc' is not on PATH and there is no executable bin/selfdoc "
        "in the project. Install it with "
        "'go install github.com/stricttools/selfdoc@v0', or name the binary with "
        "'--selfdoc <path>', and run this again."
    )


def move(project: Path, args) -> int:
    config = load_config(project)
    docs_rel, output_rel, posts_rel = declared_paths(config)
    require_tool_root(project)
    # Looked up here so the plan can name it, and demanded only by --apply,
    # right before the first write: the build that verifies the move is its
    # last step, so a binary that cannot be found would otherwise be discovered
    # with both commits already in place -- while a dry run, which builds
    # nothing, only reports what apply would refuse.
    selfdoc, selfdoc_missing = find_selfdoc(project, args.selfdoc)

    leftovers = []
    for prefix in (docs_rel, posts_rel, DEPRECATED_ROOT):
        for name in untracked_entries(project, prefix):
            if name.startswith(output_rel + "/"):
                continue
            leftovers.append(name)
    if leftovers:
        listed = "\n  ".join(sorted(set(leftovers)))
        raise Refusal(
            "these files are not tracked by git, so they cannot be moved with the rest:\n  "
            f"{listed}\nDelete what is regenerable (the caches) with "
            "'saferm delete -r --on-error abort --description \"pre-move cleanup\" <path>', "
            "or commit what is not, and run this again."
        )

    urls_before = capture_sitemap(project, output_rel, args.apply)
    # A path already at its destination is not a move: a repository part-way
    # through the move plans only what is left.
    moves = [(old, new) for old, new in plan_moves(project, docs_rel, output_rel, posts_rel)
             if old != new]
    pairs = rewrite_map(docs_rel, output_rel, posts_rel)
    manifests = plan_manifests(project, moves)

    print(f"project: {project}")
    print(f"declared today: docs={docs_rel}/ output={output_rel}/ posts={posts_rel}/")
    if selfdoc is not None:
        print(f"selfdoc binary for the verifying build: {selfdoc}")
    else:
        print("selfdoc binary for the verifying build: none found; --apply refuses "
              f"before writing anything: {selfdoc_missing}")
    print(f"sitemap URLs captured: {len(urls_before)}")
    print(f"manifests to write: {len(manifests)}")
    for relative in manifests:
        print(f"  {relative}: {MANIFEST_CONTENT.rstrip()}")
    print(f"moves planned: {len(moves)}")
    for old, new in moves:
        print(f"  {old} -> {new}")
    # A repository whose files are already in place still has its content to
    # rewrite: a run that was interrupted between the two commits finishes
    # here rather than needing the moves undone first.
    already_moved = not moves

    # The rewrite plan is read off the tree before anything is written: a file
    # that is about to move is read where it still sits and reported under the
    # name the move gives it, so the whole plan -- manifests, moves and
    # rewrites -- is known, printed and asserted before the first commit.
    rewrites = plan_rewrites(project, pairs, moves, output_rel)
    if already_moved and not rewrites:
        raise Refusal(
            "nothing to do: no tracked file sits at any of the old paths and no content "
            "names one."
        )
    if already_moved:
        print("no move is left to make; the content rewrites are what remains.")
    print(f"files to rewrite: {len(rewrites)}")
    for relative, before, after in rewrites:
        diff = changed_lines(before, after)
        print(f"  {relative}: {len(diff)} diff line(s)")
        for line in diff[:30]:
            print(f"    {line}")

    # Every stated count is checked against the plan before a single file is
    # written, so a mismatch refuses a tree nothing has touched.
    for label, planned, expected in (
        ("manifests", len(manifests), args.expect_manifests),
        ("moves", len(moves), args.expect_moves),
        ("rewrites", len(rewrites), args.expect_rewrites),
    ):
        if expected is not None and planned != expected:
            raise Refusal(f"planned {planned} {label}, expected {expected}")

    if not args.apply:
        print("dry run: nothing was moved and nothing was written.")
        return 0

    if selfdoc is None:
        raise Refusal(selfdoc_missing)
    if moves or manifests:
        perform_moves(project, moves, manifests)
    perform_rewrites(project, rewrites, output_rel)
    return verify_urls(project, selfdoc, urls_before)


def perform_moves(project: Path, moves: list[tuple[str, str]], manifests: list[str]) -> None:
    """Write the ownership manifests and move the tracked files, as one commit.

    The manifests ride the move rather than a commit of their own: the
    permission to write into a directory belongs with the files it permits, and
    a manifest left for later is a directory the repository does not carry.
    'safegit mv' commits the moves and nothing else, so the moves are made on
    disk here and declared to 'safegit commit --moved', which carries both.
    """
    for relative in manifests:
        path = project / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(MANIFEST_CONTENT, encoding="utf-8")
    for old, new in moves:
        destination = project / new
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(project / old), str(destination))

    argv = ["safegit", "commit",
            "-m", "layout: move selfdoc's directories under .stricttools/"]
    for old, new in moves:
        argv += ["--moved", f"{old} -> {new}"]
    argv.append("--")
    argv += [old for old, _ in moves]
    argv += [new for _, new in moves]
    argv += manifests
    result = run(argv, project)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    if result.returncode != 0:
        raise Refusal(f"safegit commit failed with status {result.returncode}")


def write_preserving_mode(path: Path, text: str) -> None:
    """Write a file whose mode may forbid it, and put the mode back.

    A generated root file is written read-only on purpose, and it is one of the
    files whose text names a moved path.
    """
    mode = path.stat().st_mode if path.exists() else None
    if mode is not None and not mode & 0o200:
        path.chmod(mode | 0o200)
    try:
        path.write_text(text, encoding="utf-8")
    finally:
        if mode is not None:
            path.chmod(mode)


def perform_rewrites(project: Path, rewrites, output_rel: str) -> None:
    # Every target is checked before the first one is written. A rewrite that
    # stops half-way leaves the config naming the new paths while the content
    # still names the old ones, and the old ones are then no longer derivable
    # from the config -- so the whole set is refused, or none of it is written.
    blocked = []
    for name, _, _ in rewrites:
        path = project / name
        if not path.exists():
            blocked.append(f"{name} (gone)")
            continue
        if not os.access(path.parent, os.W_OK):
            blocked.append(f"{name} (its directory is read-only)")
    if blocked:
        listed = "\n  ".join(blocked)
        raise Refusal(
            "these files cannot be rewritten, and the rewrite is all or nothing:\n  "
            f"{listed}"
        )
    written = []
    for name, _, after in rewrites:
        write_preserving_mode(project / name, after)
        written.append(name)
    if not written:
        print("no content rewrite was needed.")
        return
    argv = ["safegit", "commit", "-m",
            "layout: name the .stricttools/ paths in the moved content", "--"] + written
    result = run(argv, project)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    if result.returncode != 0:
        raise Refusal(f"safegit commit failed with status {result.returncode}")


def print_followups(project: Path) -> None:
    """The two things the person does after a successful move."""
    print("two things are left to do by hand:")
    print(f"  commit the ignore file the build derived: "
          f"safegit commit -m \"layout: the derived ignore file\" -- {ROOT_DIR}/.gitignore")
    print("  delete what the old layout left behind (build output, caches), for example:")
    print("    saferm delete -r --on-error abort --description \"superseded by the "
          ".stricttools layout\" docs/_build .selfdoc")


def verify_urls(project: Path, selfdoc: str, urls_before: set[str]) -> int:
    result = run([selfdoc, "build", "--no-auto-commit"], project)
    sys.stdout.write(result.stdout[-4000:])
    sys.stderr.write(result.stderr[-4000:])
    if result.returncode != 0:
        raise Refusal(
            "the build after the move failed. The two commits are in place; fix the "
            "build and compare the sitemap yourself."
        )
    built = project / OUTPUT_REL / "sitemap.xml"
    if not built.is_file():
        raise Refusal(
            f"the build wrote no {OUTPUT_REL}/sitemap.xml, so the URL set cannot be "
            "compared. The two commits are in place."
        )
    urls_after = sitemap_urls(built)
    if urls_after == urls_before:
        print(f"the URL set is unchanged: {len(urls_after)} addresses.")
        print_followups(project)
        return 0
    for url in sorted(urls_before - urls_after):
        print(f"  lost: {url}")
    for url in sorted(urls_after - urls_before):
        print(f"  new:  {url}")
    raise Refusal(
        "the move changed the site's URL set. The two commits are in place; the "
        "differences are listed above."
    )


if __name__ == "__main__":
    raise SystemExit(main())
